### ISSUE TITLE
[Question] The limitation of the scheduled time of scheduled message

### ISSUE THREAD

**Issue by norshtein** [Azure/azure-service-bus-go#103]
Hi, is there any limitation on the scheduled time of a scheduled message? We need a message to be visible after 3 months. I have tested with [the example](https://github.com/Azure/azure-service-bus-go/blob/master/scheduled_message_examples_test.go). I set the `waitTime` to be 3 months, the program exit without any error, and I can see "Scheduled message count" increases in "Overview" of my queue on Azure Portal. Seems it succeeded. But I'm a little bit nervous because scheduling a message after 3 months is really not a common usage... I can't find any information about this on the [quota page](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas). Could you please tell me whether I can schedule a message at 3 months later?

**Comment by devigned** [comment]
@norshtein I'll find out. I'm not sure what the max future date is. Great question!

**Comment by axisc** [comment]
@norshtein there is no limit set at the server side.
It’s technically [the max value of the DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.maxvalue?view=netframework-4.7.2)

**Comment by norshtein** [comment]
Cool. Thanks for the help!

**Comment by devigned** [comment]
@axisc thank you for the answer!
