### ISSUE TITLE
Get nil TopicEntity without error

### ISSUE THREAD

**Issue by mkfsn** [Azure/azure-service-bus-go#106]
Hi, I want to ensure the topic entity exists so I use the `TopicManager.Get()` to check it.

But then I found that `Get` method will return a nil value without an error, is that on purpose?

https://github.com/Azure/azure-service-bus-go/blob/9d787e37fa3e8fecd2d55441e257cc878e2e4ae8/topic_manager.go#L169..L171

I thought that I will always get a valid value if the error is nil in go ... please correct me if I'm wrong.

**Comment by devigned** [comment]
When thinking about 404, we evaluated a few options.
- Return nil and that is the signal that the Topic does not exist.
- Return `nil, err` where `err` would be a "not found" error.
- Return `topic, ok, err` where `err` would be real errors and ok would indicate presence.

We went with the first option intentionally. `nil` indicates 404. I think this was the least complex solution. What would you prefer? Were you surprised by the `nil` as a response?

Also related #96

**Comment by vcabbage** [comment]
My 2 cents: When returning `value, error` it's generally expected that if the error is nil the value is valid and if the error is not nil the value is invalid and should not be used. If an API has different behaviour, my expectation as a user is that it's documented. 

In this case I'd suggest the second option you describe, returning a "not found" error that users can compare or type assert if they need to determine whether the error is not found vs something else. If you were to go the type assertion route I'd also create a `IsNotFound(error) bool` function to simplify the check.

This post discusses the trade-offs of different `error` implementations: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

**Comment by mkfsn** [comment]
@vcabbage @devigned Thanks for replying, and providing such a good article :)

Yes, I'm totally agree on @vcabbage, and I think option 2 makes more sense to me. It would be better that I won't need to do a further check when/if I already check there's no errors. Does it make sense to you?

**Comment by devigned** [comment]
Ok. I'll make the change this week.

To recap, I'm going to introduce a new error type to represent a 404, which will be returned upon 404. I will also provide a func to simplifying checking for 404.

@mkfsn or @vcabbage thank you for the great discussion. You folks are awesome!
