### ISSUE TITLE
How to set ConnectivityMode

### ISSUE THREAD

**Issue by sopatwar** [Azure/azure-service-bus-go#112]
Hello,

As per the docs for Azure SDK for .NET:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.connectivitymode?view=azure-dotnet

ConnectivityMode Enum
Sets the underlying wire-level protocol used to communicate with Service Bus.

Is this possible in the Go SDK as well?

I will prefer to use AMQP over HTTPS (rather than TCP)

Thanks,
Sourabh

**Comment by devigned** [comment]
Closing this issue in favor of tracking web socket support in #93
