### ISSUE TITLE
SubscriptionWithReceiveAndDelete deletes from all subscriptions to the topic

### ISSUE THREAD

**Issue by vangent** [Azure/azure-service-bus-go#114]
* I provision a ServiceBus topic, and two subscriptions for that same topic.
* In Go, I then create two Service Bus subscriptions (corresponding to the 2 provisioned subscriptions) with the `SubscriptionWithReceiveAndDelete ` option (https://github.com/Azure/azure-service-bus-go/blob/master/subscription.go#L55). 
* I send a message to the topic.

**Expected**: Both subscriptions should get the message.
**Actual**: Only one subscription gets the message.

Both subscriptions **do** get the message without the `SubscriptionWithReceiveAndDelete` option. I'd expect that the option is semantically similar to a subscription auto-acking the message.

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions implies this as well, but isn't definitive on this particular option.

cc @vsaroopchand

**Comment by vangent** [comment]
A bit more context and sample code is here:
https://github.com/google/go-cloud/issues/1600

**Comment by devigned** [comment]
Thank you @vangent for bring up this odd behavior. I've started an internal investigation into this issue, and will report back as soon as I have some details.

**Comment by devigned** [comment]
@vsaroopchand and @vangent take a look at #115. I believe the test shows two subscriptions running with `SubscriptionWithReceiveAndDelete()` receiving two messages from a single topic. Thoughts?

**Comment by vangent** [comment]
You are right; it works. It turns out that our test was creating the same subscription twice after shortening a "too long" name by truncating the part of the name that made it unique.

Sorry for the trouble, and thanks for looking into it!

**Comment by devigned** [comment]
Great news!! Thank you for confirming.
