### ISSUE TITLE
queue.Receive() receives messages with LockedUntil expired

### ISSUE THREAD

**Issue by g-rad** [Azure/azure-service-bus-go#118]
When queue.Receive() is used and processing time is longer that queue lock duration, the messages received by handler have expired LockedUntil.

Initially I planned to use queue.Receive() with completing messages right after receiving by handler and then processing them, this way I make sure the message won't be returned to the queue if processing takes longer than lock duration.

However, with this approach messages received by the handler have already expired lock, so that on msg.Complete() amqp returns error "The lock supplied is invalid. Either the lock expired..." and the message is returned to the queue.

My question is how to receive messages if processing time is long?
Should I wait for #116 to be fixed and use queue.ReceiveOne() ?

**Comment by mcgradycchen** [comment]
Hello,

Please use ReceiveAndDeleteMode, so the message is deleted directly.

**Comment by g-rad** [comment]
Thanks @mcgradycchen.
ReceiveAndDeleteMode is a tricky option. On one hand messages will be deleted directly, so queue.Receive() will work with long processing, which is good. At the same time, in case of worker crash we will lose several messages which were taken by queue.Receive() from the queue and stored in the Receiver channel.

**Comment by devigned** [comment]
This is a tricky situation. Perhaps, I can suggest one way of approaching long running messages while minimizing chance of losing messages.

I suggest using PeekLock to receive the message, default behavior of Receive and ReceiveOne with the prefetch set to 1, also the default. Then while processing the message have a go routine to request an extension to the lock on the message. Check out [lockrenewal_test.go](./lockrenewal_test.go) for an example of how to renew message locks. Once the long running operation is complete, set the disposition of the message and continue processing the next message.

The above proposal will ensure there is only one message received from the broker at a time by having a prefetch of 1, thus ensuring no messages in queue have a lock timing out while waiting for processing. By using PeekLock, it's ensured the message will stay in the queue if processing fails for one reason or another and no disposition is set on the message.

Does this sound reasonable?

I've have a few ideas about how to make this scenario a little easier, but I don't think I've landed on the right interface. If anyone has any ideas on how they would want this to be implemented, I'd love to get some feedback / proposals.

**Comment by g-rad** [comment]
Thanks @devigned 
Renewal of active messages in a go routine sounds fine and it's definitely more reliable with PeekLock mode and prefetch=1.

**Comment by devigned** [comment]
I'm going to close this and use #68 to track the work associated with improving the lock renewal behavior.
