### ISSUE TITLE
Breaking change in go-autorest@v12.0.0

### ISSUE THREAD

**Issue by sopatwar** [Azure/azure-service-bus-go#124]
I tried to update the codebase to latest.
I'm running into the following error:

~/go/src/github.com/Azure$ go get -u github.com/Azure/azure-service-bus-go/...
# github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:98:20: future.Done undefined (type *CreateOrUpdateByIDFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:127:20: future.Done undefined (type *CreateOrUpdateFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:161:20: future.Done undefined (type *DeleteByIDFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:183:20: future.Done undefined (type *DeleteFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:616:20: future.Done undefined (type *DeploymentsCreateOrUpdateFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:645:20: future.Done undefined (type *DeploymentsDeleteFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:998:20: future.Done undefined (type *GroupsDeleteFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:1203:20: future.Done undefined (type *MoveResourcesFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:1708:20: future.Done undefined (type *UpdateByIDFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:1736:20: future.Done undefined (type *UpdateFuture has no field or method Done)
azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go:1736:20: too many errors
# github.com/Azure/azure-sdk-for-go/services/servicebus/mgmt/2017-04-01/servicebus
azure-sdk-for-go/services/servicebus/mgmt/2017-04-01/servicebus/models.go:1430:20: future.Done undefined (type *MigrationConfigsCreateAndStartMigrationFuture has no field or method Done)
azure-sdk-for-go/services/servicebus/mgmt/2017-04-01/servicebus/models.go:1459:20: future.Done undefined (type *NamespacesCreateOrUpdateFuture has no field or method Done)
azure-sdk-for-go/services/servicebus/mgmt/2017-04-01/servicebus/models.go:1488:20: future.Done undefined (type *NamespacesDeleteFuture has no field or method Done)
~/go/src/github.com/Azure$ 

Is the SDK broken upstream ?

Thanks,
Sourabh

**Comment by devigned** [comment]
Hmm... that's not good. I'll check.

Are you using go modules or just pulling latest from everything?

**Comment by sopatwar** [comment]
I'm not using go modules.

~/go/src/github.com/Azure$ go version 
go version go1.10.1 darwin/amd64

I believe modules were added in 1.11

Thanks,
Sourabh

**Comment by devigned** [comment]
I __HIGHLY__ recommend using go modules or some form of dependency management. Reproducible builds will make you so much happier.

With that said, I'll get a fix out ASAP.

@jhendrixMSFT and @Azure/go-admins looks like there's a breaking change.

**Comment by jhendrixMSFT** [comment]
This is a known issue, the breaking change was introduced in `go-autorest` v12.0.0 and `master` has not yet been updated (ETA is later today).  Pinning to v27.x.x of the SDK using `dep` will resolve this issue.
https://github.com/Azure/azure-sdk-for-go/issues/4579

**Comment by devigned** [comment]
@jhendrixMSFT, thank you for the quick response!

**Comment by sopatwar** [comment]
Thanks for all the responses!
Will wait for master to be updated and then test #123 

-Sourabh

**Comment by bitfield** [comment]
> Pinning to v27.x.x of the SDK using dep will resolve this issue

This doesn't seem to help:

```
go: finding github.com/Azure/azure-sdk-for-go v27.0.0
go: finding github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute latest
go: finding github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01 latest
go: finding github.com/Azure/azure-sdk-for-go/services/compute/mgmt latest
go: finding github.com/Azure/azure-sdk-for-go/services/compute latest
go: finding github.com/Azure/azure-sdk-for-go/services latest
# github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2008:20: future.Done undefined (type *ContainerServicesCreateOrUpdateFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2037:20: future.Done undefined (type *ContainerServicesDeleteFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2499:20: future.Done undefined (type *DisksCreateOrUpdateFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2527:20: future.Done undefined (type *DisksDeleteFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2550:20: future.Done undefined (type *DisksGrantAccessFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2587:20: future.Done undefined (type *DisksRevokeAccessFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2609:20: future.Done undefined (type *DisksUpdateFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2733:20: future.Done undefined (type *GalleriesCreateOrUpdateFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:2762:20: future.Done undefined (type *GalleriesDeleteFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:3219:20: future.Done undefined (type *GalleryImagesCreateOrUpdateFuture has no field or method Done)
/Users/john/go/pkg/mod/github.com/!azure/azure-sdk-for-go@v27.3.0+incompatible/services/compute/mgmt/2019-03-01/compute/models.go:3219:20: too many errors
```

**Comment by jhendrixMSFT** [comment]
Are you using `dep` to manage the dependencies?  v27.3.0 of the SDK relies on v11.9.0 of go-autorest which still contains the `Done()` method.
https://github.com/Azure/azure-sdk-for-go/blob/master/Gopkg.toml#L28

**Comment by bitfield** [comment]
No `dep`, just Go. I've tried:

```
go get github.com/Azure/go-autorest@v12.0.0
```

That works, but the build still fails with the same errors.

**Comment by jhendrixMSFT** [comment]
Can you use v11.9.0?

**Comment by bitfield** [comment]
Yes, v11.9.0 works, thank you.

**Comment by devigned** [comment]
@jhendrixMSFT when do you think there will be a tagged release of Azure SDK for Go that will use go-autorest@v12.0.0?

**Comment by jhendrixMSFT** [comment]
Hopefully today.

**Comment by jhendrixMSFT** [comment]
Done https://github.com/Azure/azure-sdk-for-go/releases/tag/v28.0.0

**Comment by sopatwar** [comment]
@jhendrixMSFT Thanks!
