### ISSUE TITLE
`unexpected module path "golang.ord/x/lint"` on `make all`

### ISSUE THREAD

**Issue by stianlagstad** [Azure/azure-service-bus-go#132]
Hi,

I'm believe I'm running into [this issue](https://github.com/golang/lint/issues/436) when running `make all`:
```
➜  uname -a
Linux stian-Precision-5530 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
➜  go version
go version go1.12.4 linux/amd64
➜  pwd
/home/stian/go/src/github.com/Azure/azure-service-bus-go
➜  make all
▶ running gofmt…
▶ building golint…
go: finding github.com/golang/lint/golint latest
go: finding github.com/golang/lint latest
go: github.com/golang/lint@v0.0.0-20190409202823-959b441ac422: parsing go.mod: unexpected module path "golang.org/x/lint"
go: error loading module requirements
Makefile:28: recipe for target '/home/stian/go/bin/golint' failed
make: *** [/home/stian/go/bin/golint] Error 1
```

Is there something I can do to bypass that?

I'm new to golang and to this library, so please don't hesitate to close this issue and tell me to debug further myself.

**Comment by stianlagstad** [comment]
I of course figured out a way to solve it a couple of minutes after creating the issue. After doing `go get -u golang.org/x/lint/golint` to install golint on my system, `make all` got past that error and succeeded.

I do see golint mentioned in the [contributing](https://github.com/Azure/azure-service-bus-go/blob/master/CONTRIBUTING.md) page, but could it also be worth modifying the `Makefile` to output a better error for this specific case, and/or add a `How to build this project` section in the readme?

**Comment by devigned** [comment]
Noted and will address time willing :).

**Comment by jhendrixMSFT** [comment]
This has been fixed.
