### ISSUE TITLE
How to get a hold of this module's logs?

### ISSUE THREAD

**Issue by stianlagstad** [Azure/azure-service-bus-go#133]
Hi,

Id like to see the logs that this module outputs (specifically [this one](https://github.com/Azure/azure-service-bus-go/blob/master/sender.go#L198). I see that azure-service-bus-go makes use of [azure-amqp-common-go](https://github.com/Azure/azure-amqp-common-go) and [its logger](https://github.com/Azure/azure-amqp-common-go/blob/master/log/logger.go#L58). Is there a way I could inject my own logger here, or provide my own implementations of the `func (sl nopLogger)`-methods?

Thank you very much!

**Comment by devigned** [comment]
The logging is a bit in flux right now. I need to move [azure-amqp-common-go](https://github.com/Azure/azure-amqp-common-go) over to using a [tracing / logging abstraction](https://github.com/devigned/tab). By using `devigned/tab`, you would be able to provide your own `Tracer` implementation or use OpenCensus or OpenTracing.

What do you think?

**Comment by stianlagstad** [comment]
Thank you for the answer! That sounds like a good idea to me.

**Comment by devigned** [comment]
Ok, now that `v0.8.0` is released, you can leverage `github.com/devigned/tab` and `github.com/devigned/tab/opencensus` or `github.com/devigned/tab/opentracing` to collect logs and traces.

A good example of setting this up is the [testhub command line tool](https://github.com/devigned/testhub). I use `testhub` to execute some long running tests against event hubs, but the setup is the same for service bus.

The key to setup below is the `_ "github.com/devigned/tab/opencensus"` where that imports and registers the OpenCensus `Tracer` with `github.com/devigned/tab` and the method to initialize the Jaeger exporter `initOpenCensus`.
```go 
import (
	"fmt"
	"os"

	_ "github.com/devigned/tab/opencensus"

	"contrib.go.opencensus.io/exporter/jaeger"
	"go.opencensus.io/trace"

	"github.com/devigned/testhub/cmd"
)

func main() {
	if os.Getenv("TRACING") == "true" {
		closer, err := initOpenCensus()
		if err != nil {
			fmt.Println(err)
			return
		}
		defer closer()
	}

	cmd.Execute()
}

func initOpenCensus() (func(), error) {
	exporter, err := jaeger.NewExporter(jaeger.Options{
		AgentEndpoint:     "localhost:6831",
		CollectorEndpoint: "http://localhost:14268/api/traces",
		Process: jaeger.Process{
			ServiceName: "testhub",
		},
	})

	if err != nil {
		return nil, err
	}

	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
	trace.RegisterExporter(exporter)
	return exporter.Flush, nil
}
```

With that setup, you should be able to see traces of all of the functions as well as log entries associated with those function spans.

If this is solves your issue, please comment and close. If not, let me know what more you'd like to see done.

Thanks!

**Comment by devigned** [comment]
I'm going to close this issue since I think the original question has been answered. However, I'm going to add a doc page which provides this information in a more discoverable and easier to digest form.

**Comment by stianlagstad** [comment]
Thank you very much @devigned ! I do not have time to test this now, but we will use this :)
