### ISSUE TITLE
Azure MSI Support

### ISSUE THREAD

**Issue by patnaikshekhar** [Azure/azure-service-bus-go#136]
**Feature Request**

It would be very useful to have MSI (Managed Service Identity) support in this library. An example would be

```go
ns, err := servicebus.NewNamespace(servicebus.NamespaceFromMSI())
if err != nil {
    fmt.Println(err)
    return
}
```

**Comment by devigned** [comment]
Good catch! I had been meaning to an environmental configuration like Event Hubs has (https://github.com/Azure/azure-event-hubs-go/blob/64aa20d6c1260df9c7fc558e6892adc9bec9ff9f/hub.go#L358-L401). With that said, you could use the JWT (https://github.com/Azure/azure-amqp-common-go/blob/v1.1.0/aad/jwt.go) token provider in Service Bus to achieve the same result prior to me adding the feature as a constructor option.

```go
ns, err := servicebus. NewNamespace()
if err != nil {
  fmt.Println(err)
  return
}

// this will configuration the Azure Active Directory token provider to probe the env for
// Service Principal credentials or for a Managed Identity service running on the instance
provider, err := aad. NewJWTProvider(aad.JWTProviderWithEnvironmentVars())
if err != nil {
  fmt.Println(err)
  return
}

ns.TokenProvider = provider
ns.Name = "your service bus namespace name"

// do whatever you wanted to do
```

If you are interested, I'd be happy to review a PR with this functionality.

**Comment by patnaikshekhar** [comment]
Thanks @devigned that seemed to work. I'll send across a pull request next week!

**Comment by patnaikshekhar** [comment]
@devigned I seem to be getting a different error now - FATAL:  unhandled error link XXXXX status code 401 and description: InvalidAudience: Invalid authorization token audience. TrackingId:XXXXXXXX, SystemTracker:NoSystemTracker, Timestamp:2019-07-19T14:18:23

I don't think that the generated token has the audience set to https://servicebus.azure.net

**Comment by devigned** [comment]
Oh no... you are correct!

```go
// this will configuration the Azure Active Directory token provider to probe the env for
// Service Principal credentials or for a Managed Identity service running on the instance
provider, err := aad.NewJWTProvider(
  aad.JWTProviderWithEnvironmentVars(),
  aad.JWTProviderWithResourceURI("https://servicebus.azure.net/"))
if err != nil {
  fmt.Println(err)
  return
}
```

**Comment by patnaikshekhar** [comment]
Strangely I'm getting the same error
FATAL:  unhandled error link 4f2e89fc-af4e-45ce-a767-9be2e9e60fe9: status code 401 and description: InvalidAudience: Invalid authorization token audience. TrackingId:d012a242-2528-4a3b-bac2-855d2315f96c, SystemTracker:NoSystemTracker, Timestamp:2019-07-20T22:17:00

This is what I have so far
```go
// NamespaceFromMSI configures a namespace from the environment (variables or MSI)
func NamespaceFromMSI(name string) NamespaceOption {
	return func(ns *Namespace) error {
		provider, err := aad.NewJWTProvider(
			aad.JWTProviderWithEnvironmentVars(),
			aad.JWTProviderWithResourceURI(serviceBusResourceURI),
		)
		if err != nil {
			return err
		}

		fmt.Println(provider.GetToken(serviceBusResourceURI))

		ns.TokenProvider = provider
		ns.Name = name
		return nil
	}
}
```
This is my sample code that I'm testing with
```go
        ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	ns, err := servicebus.NewNamespace(servicebus.NamespaceFromMSI("sample"))
	if err != nil {
		panic(err)
	}

	q, err := ns.NewQueue("sample")
	if err != nil {
		fmt.Println("FATAL: ", err)
		return
	}

	err = q.Send(ctx, servicebus.NewMessageFromString("Hello, World!!!"))
	if err != nil {
		fmt.Println("FATAL: ", err)
		return
	}
```

**Comment by devigned** [comment]
Looks like the audience is incorrect. This is the string specified by `serviceBusResourceURI`. I think I omitted the end "/" when I specified it in the previous reply. Based on the [SB JS lib](https://github.com/Azure/azure-sdk-for-js/blob/550f9596a7d1055f6a6f03bb54cff262431aaab0/sdk/servicebus/service-bus/src/serviceBusClient.ts#L233), I'm thinking it should be "https://servicebus.azure.net/". 

**The trailing slash is significant.**

**Comment by patnaikshekhar** [comment]
@devigned good catch. It works now! Thanks a lot.

**Comment by gavinfish** [comment]
> Managed identities for Azure resources is the new name for the service formerly known as Managed Service Identity (MSI).

`MSI` is deprecated, we may not use it in a public method name any more. Details at [About managed identities for Azure resources](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).

**Comment by richardpark-msft** [comment]
Closing this issue as it looks like the original problem was resolved.

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus) but I believe this naming problem is not an issue since we mainly leverage `azidentity`, so no MSI terminology should be leaking into our public surface.
