### ISSUE TITLE
Parallel sending batch messages may get nil pointer exception

### ISSUE THREAD

**Issue by gavinfish** [Azure/azure-service-bus-go#141]
[sample code](https://github.com/VSChina/testbus/blob/master/cmd/max_send.go)

Step to reproduce:
1. build the testbus project
2. run command `testbus max-send --conn-str="***"`

For a while, error like below will be thrown:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x71fade]

goroutine 11 [running]:
pack.ag/amqp.(*Sender).send(0x0, 0xbec380, 0xc0002623f0, 0xc0002655f0, 0x0, 0x0, 0x0)
        D:/go/pkg/mod/pack.ag/amqp@v0.11.2/client.go:377 +0x17e
pack.ag/amqp.(*Sender).Send(0x0, 0xbec380, 0xc0002623f0, 0xc0002655f0, 0x0, 0x0)
        D:/go/pkg/mod/pack.ag/amqp@v0.11.2/client.go:351 +0x6e
github.com/Azure/azure-service-bus-go.(*Sender).trySend(0xc0000fe070, 0xbec380, 0xc0002623f0, 0xbe7b80, 0xc000262330, 0x0, 0x0)
        D:/go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.9.1/sender.go:205 +0x323
github.com/Azure/azure-service-bus-go.(*Queue).SendBatch(0xc00002dc00, 0xbec380, 0xc0005d0150, 0xbe1f40, 0xc0005d0120, 0x0, 0x0)
        D:/go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.9.1/queue.go:196 +0x23d
github.com/VSChina/testbus/cmd.(*repeatSender).Run(0xc0002625d0, 0xbec2c0, 0xc000073480, 0xc000224200, 0xc000058780, 0xc000058720)
        D:/go/src/github.com/VSChina/testbus/cmd/max_send.go:72 +0x2fe
created by github.com/VSChina/testbus/cmd.glob..func8
        D:/go/src/github.com/VSChina/testbus/cmd/max_send.go:124 +0x419
```

It seems that a service bus Sender is detached from its amqp sender.

**Comment by devigned** [comment]
There needs to be a reader lock in place when the sender is sending, so that if an error is encountered and the sender (connection, session, link) needs to be recreated, it will do so in an atomic manor. 

I expect this is happening when a send fails due to error in one of the senders and `sender.Recover` is called. `Recover` calls `Close`, which then nils the amqp related fields. `Recover` then rebuilds the connection. If `Recover` is called in one thread while send is being called in another, this could very easily cause the error above. I think the rpc client handles this a bit better: https://github.com/Azure/azure-service-bus-go/blob/master/rpc.go.

**Comment by gavinfish** [comment]
@devigned Agree, there are some throttle restriction on the service side, so sending lots of messages in parallel may fail sometimes.

And this issue seems to be caused by failing to recover the session and link. [code](https://github.com/Azure/azure-service-bus-go/blob/e1e88bc99d4cc930056f18c8a4671f259d0d2336/sender.go#L218) here just sends debug span instead of dealing with the situation. Should we add retry strategy or just return err when it fails to recover?

**Comment by gavinfish** [comment]
Details about the error messages:

**Throttle error**
```
"*Error{Condition: com.microsoft:server-busy, Description: The request was terminated because the namespace azuresbtests-fqfclayc is being throttled. Error code : 50009. Please wait 10 seconds and try again. Reference:3f49ca31-e885-4491-853d-ffaa8293c013, TrackingId:1a2c36240000000a0024729e5d39641b_G17_B2, SystemTracker:azuresbtests-fqfclayc:Queue:max-send-codvkdzlfb, Timestamp:2019-07-25T08:11:16, Info: map[]}
```

**Recover error**
```
The operation did not complete within the allocated time 00:01:00 for object attach. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:13343f6cf52d4bd48562fbf964d4c873_G17, SystemTracker:gateway7, Timestamp:2019-07-25T10:43:10
```

**Comment by devigned** [comment]
I have not seen that error on attach! Interesting...

I think you are right, we should attempt to recover the connection again as long as the context has not expired. Do you agree?

**Comment by gavinfish** [comment]
Agree. And I prefer to implement similar logic as [receiver](https://github.com/Azure/azure-service-bus-go/blob/e1e88bc99d4cc930056f18c8a4671f259d0d2336/receiver.go#L296-L323) does.
