### ISSUE TITLE
batch disposition doUpdate returns unexpected result

### ISSUE THREAD

**Issue by jakebjorkekato** [Azure/azure-service-bus-go#145]
When calling `SendBatchDisposition` [here](https://github.com/Azure/azure-service-bus-go/blob/master/entity.go#L207)

It uses `doUpdate` [here](https://github.com/Azure/azure-service-bus-go/blob/master/batch_disposition.go#L69)

The issue is that a zero value is returned for the error, which isn't expected behavior in go.

For a calling function that operates normally you can expect this code

```golang
err := s.SendBatchDisposition(ctx, iter)
if err != nil {
    return fmt.Errorf("unable to update dispostion:  %v", err)
}

//do more stuff
```

The current implementation will never get to the `//do more stuff` section.

**Comment by devigned** [comment]
Yeah... that’s definitely wrong. Thanks for the issue!
