### ISSUE TITLE
Dependency error with dep

### ISSUE THREAD

**Issue by fmsolana** [Azure/azure-service-bus-go#150]
I'm using dep to calculate dependencies and I get this error:

init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/Azure/azure-amqp-common-go met constraints:
	v2.1.0: Could not introduce github.com/Azure/azure-amqp-common-go@v2.1.0 due to multiple problematic subpackages:
	Subpackage github.com/Azure/azure-amqp-common-go/v2 is missing. (Package is required by github.com/Azure/azure-service-bus-go@v0.9.1.)	Subpackage github.com/Azure/azure-amqp-common-go/v2/auth is missing. (Package is required by github.com/Azure/azure-service-bus-go@v0.9.1.)	Subpackage github.com/Azure/azure-amqp-common-go/v2/cbs is missing. (Package is required by github.com/Azure/azure-service-bus-go@v0.9.1.)	Subpackage github.com/Azure/azure-amqp-common-go/v2/conn is missing. (Package is required by github.com/Azure/azure-service-bus-go@v0.9.1.)	Subpackage github.com/Azure/azure-amqp-common-go/v2/rpc is missing. (Package is required by github.com/Azure/azure-service-bus-go@v0.9.1.)	

In the docuementations of common there are a reference for  common v2 but doesn't work

https://github.com/Azure/azure-amqp-common-go

Using go get targeting version 2.x.x
go get -u github.com/Azure/azure-amqp-common-go/v2

go get -u github.com/Azure/azure-amqp-common-go/v2
package github.com/Azure/azure-amqp-common-go/v2: cannot find package "github.com/Azure/azure-amqp-common-go/v2" in any of:
	/snap/go/4762/src/github.com/Azure/azure-amqp-common-go/v2 (from $GOROOT)
	$GOPATH/go/src/github.com/Azure/azure-amqp-common-go/v2 (from $GOPATH)

I have to say that after several execution of 
dep init

some times resolve the version with this.

github.com/Azure/azure-amqp-common-go               ^1.1.4         v1.1.4         b5ea482   unknown  10  
github.com/Azure/azure-service-bus-go               ^0.7.0         v0.7.0         b2e3e7e   unknown  2

**Comment by mcgradycchen** [comment]
Hi @fmsolana, I have a exact same issue.  Did you resolve the problem with version 0.9.1?

**Comment by mcgradycchen** [comment]
Hi @devigned , after I upgrade my go version to 1.13.4, I can use command `go get -u github.com/Azure/azure-service-bus-go` to install successfully.
But, I have another when I use `dep`, the error output are 

try github.com/Azure/azure-amqp-common-go@v2.1.0
(3)	✗   github.com/Azure/azure-amqp-common-go at v2.1.0 has problem subpkg(s):
(3)	  	github.com/Azure/azure-amqp-common-go/v2 is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.	github.com/Azure/azure-amqp-common-go/v2/auth is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.	github.com/Azure/azure-amqp-common-go/v2/cbs is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.	github.com/Azure/azure-amqp-common-go/v2/conn is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.	github.com/Azure/azure-amqp-common-go/v2/rpc is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.	github.com/Azure/azure-amqp-common-go/v2/sas is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.	github.com/Azure/azure-amqp-common-go/v2/uuid is missing; required by github.com/Azure/azure-service-bus-go@v0.9.1.

**Comment by devigned** [comment]
Please consider moving to Go modules. I think using `dep` with versioned modules is going to lead to pain.

You can use previous version of this library which take a pre v2.0 dependency on azure-amp-common-go, but later version of this library will break when using `dep`.

This is a systemic issue. See also: https://github.com/golang/dep/issues/2139
