### ISSUE TITLE
ServiceBus.Subscribe is exiting

### ISSUE THREAD

**Issue by JosephK9** [Azure/azure-service-bus-go#157]
ns,err = servicebus.NewNamespace(servicebus.NamespaceWithEnvironmentBinding(namespace))

Using environment Binding connecting to servicebus subscribe method is exiting  whereas publish and delete are working

**Comment by richardpark-msft** [comment]
Hi @JosephK9,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

As part of moving into azure-sdk-for-go repo we've also integrated with the `azidentity` package. An example of this is here: [example](https://github.com/Azure/azure-sdk-for-go/blob/c5b9d7c743aee9d01c26907e6923605b7096c51b/sdk/messaging/azservicebus/example_client_test.go#L15).

Using `azidentity`, in the new package `azservicebus` I'm not able to reproduce this issue.

If you are interested in trying this this migration guide should help: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md
