### ISSUE TITLE
messageFromAMQMessage panic on empty payloads

### ISSUE THREAD

**Issue by sam-at-luther** [Azure/azure-service-bus-go#159]
I have not been able to reproduce this, however we've seen panics due to this line in message.go master (`1839bfc2a41a03ac130d55a1715188d3c0552f07`)

`func messageFromAMQPMessage(msg *amqp.Message) (*Message, error) {
	return newMessage(msg.Data[0], msg)
}
`
where msg.Data is nil.

**Comment by sam-at-luther** [comment]
https://github.com/Azure/azure-service-bus-go/pull/160 relates to this issue

**Comment by jhendrixMSFT** [comment]
This has been fixed in v0.10.2, sorry it took so long.
