### ISSUE TITLE
Consuming more than one message from the dead-letter queue

### ISSUE THREAD

**Issue by davidkuridza** [Azure/azure-service-bus-go#161]
There is a difference in how the messages are consumed from the queue and the dead-letter queue:

```go
// queue
ReceiveOne(ctx context.Context, handler Handler) error
Receive(ctx context.Context, handler Handler) error

// dead-letter queue:
ReceiveOne(ctx context.Context, handler Handler) error
```

Is there a reason for not being able to receive more than one message from the dead-letter queue?

**Comment by richardpark-msft** [comment]
Hi @davidkuridza,

Development of this package has moved to the azure-sdk-for-go [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

This particular design issue was something we addressed in the new API for the Receiver. Receiver's are now no longer different when you open a dead letter queue vs just a queue.

* [Creating a receiver for a non-dead letter queue](https://github.com/Azure/azure-sdk-for-go/blob/49619d81888257e45ba7a219f2a57d59efb5e4c0/sdk/messaging/azservicebus/example_receiver_test.go#L26)
* [Creating a receiver for a dead letter queue](https://github.com/Azure/azure-sdk-for-go/blob/49619d81888257e45ba7a219f2a57d59efb5e4c0/sdk/messaging/azservicebus/example_receiver_test.go#L36)

**Comment by davidkuridza** [comment]
@richardpark-msft thank you!
