### ISSUE TITLE
the receiver.go file has an issue

### ISSUE THREAD

**Issue by eshanchawla0403** [Azure/azure-service-bus-go#163]
the receiver.go file has an import for ""github.com/Azure/azure-amqp-common-go/v3""

I am not able to find the v3 package when I browse to azure-amqp-common-go folder. I am new to golang and may be missing something very obvious. Can someone please help.

**Comment by bvwells** [comment]
@eshanchawla0403 the name of the module defined in the go.mod file on the master branch of the repo is named:

github.com/Azure/azure-amqp-common-go/v3

See
https://github.com/Azure/azure-amqp-common-go/blob/master/go.mod

Hope this helps

**Comment by jhendrixMSFT** [comment]
Closing as I believe this has been addressed but do let us know if you have further questions.
