### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by eaardal** [Azure/azure-service-bus-go#167]
Doesn't seem like there's been any activity since last year. Just curious since my team is waiting for some bugfixes and we're starting to consider other solutions.

**Comment by jhendrixMSFT** [comment]
Hello!  Sorry for the lack of inactivity.  I've merged the most recent PRs and tagged a new release.  Were there other fixes you're looking for?

**Comment by ianaz** [comment]
Sorry to write here. I thought this issue is more appropriate to ask my question. What's the difference between https://github.com/Azure/go-amqp and this repository? Is go-amqp deprecated?

**Comment by devigned** [comment]
go-amqp is the "protocol library". That library implements the AMQP 1.0 protocol, and could be used with any AMQP 1.0 compatible broker, not just Service Bus or Event Hub.

This library is intended to provide a client interface which exposes features specific to Azure Service Bus which are implemented via AMQP.

I think the best analogy is this library is the client interface for a specific REST API and go-amqp would be like the underlying HTTP library which the REST client depends upon.

**Comment by ianaz** [comment]
Thanks @devigned ! this cleared things up :)

**Comment by crussell52** [comment]
Just checking in on the original topic of "Is this repo dead?"  Sorting issue activity by "recently updated" reveals this as the one with the most recent comments from members.

While I'm here, I'll mention #171 (info on end of preview) since the topics are related.

**Comment by jhendrixMSFT** [comment]
While the repo isn't dead, the Go SDK team is a small team (two people) and to be frank service bus hasn't been our priority as we've been busy with other deliverables.

I will work with our management team to see how we can carve out a bit more time to follow up on issues here.

**Comment by crussell52** [comment]
thank you for your candid response -- gives me some context for making a product choice for our solution. 👍

**Comment by gerhardcit** [comment]
@jhendrixMSFT , is there anywhere else than service bus that you would suggest we look at? (In the Azure space)

**Comment by jhendrixMSFT** [comment]
For an Azure service bus implementation?  I'm not aware of another implementation, however that doesn't mean one isn't out there (let me know if I misunderstood your question).

I'm hoping that in the coming weeks we'll have a bit more time to dedicate to SB (and event hubs).

**Comment by jhendrixMSFT** [comment]
I'm going to close this with the following statements.

- the repo isn't dead however we aren't investing in any new features at this time
- will keep an eye on PRs, please tag myself and @catalinaperalta when you open one
- crashes/hangs/data-loss type issues will be top priority as time permits
- we're a small team so things will likely move slow
