### ISSUE TITLE
SAS Policy on topics

### ISSUE THREAD

**Issue by Diastro** [Azure/azure-service-bus-go#170]
Is there a way to add a new SAS Policy on Topics in go? I've looked around in the sdk and I cannot find an equivalent to : https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#access-shared-access-authorization-rules-on-an-entity

**Comment by richardpark-msft** [comment]
Hi @Diastro, 

Development of this library has moved into the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus)

I have an issue tracking this same feature, however, which will be added:
https://github.com/Azure/azure-sdk-for-go/issues/16045
