### ISSUE TITLE
Need info on production availability of Service Bus for Golang

### ISSUE THREAD

**Issue by MaheshDevireddy** [Azure/azure-service-bus-go#171]
Hi Team,

We are looking forward for using Service Bus with subscriber implementation with Golang. The github documentation says that this is currently available only in preview as in this link: https://github.com/Azure/azure-service-bus-go#preview-of-service-bus-for-golang.

Can you please let us know when will this be available in production as we cannot go live with the preview version. Our plan is to go to production in 2 months and any info on the prod timelines of Service Bus for Golang is appreciated. Thank you.

**Comment by richardpark-msft** [comment]
Hello @MaheshDevireddy,

We're working towards a GA in the azure-sdk-for-go repo [azservicebus](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus) package. 

I don't have a production timeline that I can share, however, but we are actively working on this package and will take any feedback. 

We have a migration guide to help ease transition: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md
