### ISSUE TITLE
Error calling ReceiveOne()

### ISSUE THREAD

**Issue by jovillas** [Azure/azure-service-bus-go#174]
I'm receiving an error from ReceiveOne() function that just forwards what appears to be a server-side error or an amqp dependency error back to the user. The error clearly ask to retry.
```
Error{Condition: amqp:internal-error, Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:c0b7e7503450451bab1d89efb262461c_G13, SystemTracker:gateway5, Timestamp:2020-06-25T23:56:38, Info: map[]}
```

The only way for the user of azure-service-bus-go to handle this error and retry is to actually parse the error text. That is not a very useful API.

Can you either add a isRetriable(error) function or an error type we can check against to know if this error is retriable or should be handled as an unexpected error?

**Comment by richardpark-msft** [comment]
Hi @jovillas, 

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

To your original request, it makes absolute sense. We have an issue to tackle exactly this in the new package: https://github.com/Azure/azure-sdk-for-go/issues/15610.
