### ISSUE TITLE
Add ability to verify entity type with restricted permissions

### ISSUE THREAD

**Issue by princjef** [Azure/azure-service-bus-go#176]
When working with restricted Send permissions, there is no way today to verify through the SDK that the entity you're working with is of a specific type (i.e. queue vs topic). Similarly, it's possible in many cases to pass connection information for an Event Hub and still have it work for some scenarios but not others.

The .NET SDK makes a distinction between trying to do general purpose sending and creating a specific "topic" or "queue" client. The latter includes an additional assertion on link attach that states the expected type of the entity (i.e. queue or topic), which will cause the server to fail the connection attempt if the entity is of the wrong type. This is particularly useful when trying to verify dynamic input in advanced usage scenarios.

Adding support for this involves including a link property with name `com.microsoft:entity-type` and a value of `0` for queue and `1` for topic when establishing the link. One crucial detail: the link property _must_ be encoded as an "int" (int32) in AMQP for Service Bus to read and enforce the entity type. This would require an addition to the go-amqp package (see https://github.com/Azure/go-amqp/pull/8).

Adding this to the existing package as a default validation when creating a queue or topic client would technically be breaking, so not sure whether it makes more sense to hold the change for the next breaking version or expose it through a new option on `NewQueue`/`NewTopic`.

**Comment by serbrech** [comment]
Thanks for reporting this with pointers towards the implementation. Note that PRs are welcome ;)

**Comment by richardpark-msft** [comment]
Hi @princjef, 

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

With regards to this particular request, the newest set of Azure Service Bus SDKs no longer use an "entity" style object layout (ie, QueueClient, TopicClient, etc..) and have moved more towards representing things as Receivers/Senders instead. This means that the Senders no longer distinguish in any way between queues or topics. 

I'd like to understand your requirement a bit more as this is not usually seen as an issue - sending to a topic or queue is intended to be very similar, if not indistinguishable. 

This repo is going to be archived, so if you want to continue this discussion please file an issue at https://github.com/Azure/azure-sdk-for-go/issues and I'd be more than happy to hash things out.
