### ISSUE TITLE
Queue.Send receiving amqp:internal-error error if PartitionKey is set

### ISSUE THREAD

**Issue by g-rad** [Azure/azure-service-bus-go#178]
We are using v0.9.1 to send messages to a service bus queue. A few hours ago today our code that calls Queue.Send has stuck indefinitely. Further investigation revealed that Sender.trySend receiving an amqp.Error with following attributes:
* Condition: amqp:internal-error
* Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101
* Info: nil

The queue we are using has partitioning enabled.

If I comment a couple of lines below the message will be sent successfully:
```
msg.SystemProperties = &servicebus.SystemProperties{}
msg.SystemProperties.PartitionKey = &stringBrandId
```

Updating to v0.10.3 doesn't solve the issue.

Any ideas why providing the partition key prevents a message from being sent all of a sudden?

The issue can be reproduced with this code
```
func main() {
	connStr := "Endpoint=sb://xxx.servicebus.windows.net/;SharedAccessKeyName=yyy;SharedAccessKey=zzz"
	queueName := "test-queue"

	ns1, err := servicebus.NewNamespace(servicebus.NamespaceWithConnectionString(connStr))
	if err != nil {
		panic(err)
	}

	q, err := ns1.NewQueue(queueName)
	if err != nil {
		panic(err)
	}

	defer func() {
		if err := q.Close(context.Background()); err != nil {
			log.Println("error closing queue", err)
		}
	}()

	partitionKey := "a"

	msg := servicebus.NewMessageFromString("hello")
	msg.SystemProperties = &servicebus.SystemProperties{}
	msg.SystemProperties.PartitionKey = &partitionKey

	// q.Send will never finish
	if err := q.Send(context.Background(), msg); err != nil {
		panic(err)
	}

	log.Println("sent")
}
```

**Comment by devigned** [comment]
Are you batching the messages?

**Comment by g-rad** [comment]
@devigned no, we are not. I added an example of the code to reproduce the issue.

**Comment by richardpark-msft** [comment]
(NOTE: We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus))

I've attempted to reproduce this issue using the new package and am unable to. We have a specific test case that covers this functionality: [test](https://github.com/Azure/azure-sdk-for-go/blob/c5b9d7c743aee9d01c26907e6923605b7096c51b/sdk/messaging/azservicebus/sender_test.go#L79)

If you're willing to use the new package we have a migration guide to help transition: [migrationguide.md](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md)
