### ISSUE TITLE
Examples reference  missing ensureQueue function

### ISSUE THREAD

**Issue by ethanmcc** [Azure/azure-service-bus-go#191]
Several examples reference calls to the function `ensureQueue` – where can this be found?

**Comment by devigned** [comment]
https://github.com/Azure/azure-service-bus-go/blob/27d94af5a749d428c24874e589ca176a104e5da6/auto_forward_example_test.go#L81

**Comment by ethanmcc** [comment]
thanks! it looks like my github searches missed the function declaration.

**Comment by devigned** [comment]
Same with regard to the GH searches. The func is also in a weird place, so that adds to the pain of finding it. 

It's too bad examples can't include multiple funcs.
