### ISSUE TITLE
Websocket behind Proxy issue

### ISSUE THREAD

**Issue by ProfessorMc** [Azure/azure-service-bus-go#194]
"golang.org/x/net/websocket" doesn't honor http_proxy, https_proxy, etc.  This means connections behind corporate proxy will fail.

"golang.org/x/net/websocket" documentation suggests that a richer feature set can be found in "nhooyr.io/websocket" or the gorilla implementation.

go version go1.15 windows/amd64
github.com/Azure/azure-service-bus-go v0.10.6

**Comment by jhendrixMSFT** [comment]
Fixed in v0.10.7
