### ISSUE TITLE
Service interruption causes panic

### ISSUE THREAD

**Issue by eccles** [Azure/azure-service-bus-go#203]
Azure periodically  suffers from poor reliability with upstream service bus  returning errors.

When calling Recive() and these errors occur a panic() occur because of a nil pointer in the go-amqp package.:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94d42a]

goroutine 977 [running]:
github.com/Azure/go-amqp.(*Receiver).Receive(0x0, 0xe0c140, 0xc00035e840, 0xceebd3, 0x1c, 0xe0c140)
	/opt/go/pkg/mod/github.com/!azure/go-amqp@v0.12.6/client.go:1864 +0x3a
github.com/Azure/azure-service-bus-go.(*Receiver).listenForMessage(0xc0004413f0, 0xe0c140, 0xc00035e840, 0x0, 0x0, 0x0)
	/opt/go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.10.2/receiver.go:339 +0xfe
github.com/Azure/azure-service-bus-go.(*Receiver).listenForMessages(0xc0004413f0, 0xe0c140, 0xc00035e840, 0xc000768780)
	/opt/go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.10.2/receiver.go:291 +0xf2
created by github.com/Azure/azure-service-bus-go.(*Receiver).Listen
	/opt/go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.10.2/receiver.go:213 +0x144

with an error in the handler when trying to Complete the message:

Complete Message Failure err='amqp: connection closed' 

This a serious bug - segmentation failutes should never happen.

**Comment by jhendrixMSFT** [comment]
There was a fix for this, see https://github.com/Azure/azure-service-bus-go/pull/187.  I don't know what version of this SDK you're using,  however the version of `go-amqp` in the above stack trace suggests that you don't have this fix (it first appeared in `v0.10.5` which drags in a newer version of `go-amqp` than what's listed here).  Given this, I'm going to close this issue.  If you get a repro of this fault with a recent version please ping back here.

**Comment by eccles** [comment]
I have just checked and we are using g-amqp 0.13.1 - however we only recently upgraded (29th Jan) all our MS versions (azure-service-bus went from 0.10.2 to 0.10.9). 

So leave it closed - thanks for your attention...
