### ISSUE TITLE
Correlation filter rule with user properties returns error "xml: unsupported type: map[string]interface {}"

### ISSUE THREAD

**Issue by wzamlynny** [Azure/azure-service-bus-go#204]
Creating a filter rule using a [correlation filter](https://github.com/Azure/azure-service-bus-go/blob/78c960db000c65f4e32d01371b496d5b33f59c38/filter.go#L25) on a subscription with custom user properties returns error:  `xml: unsupported type: map[string]interface {}` on [PutRule](https://github.com/Azure/azure-service-bus-go/blob/78c960db000c65f4e32d01371b496d5b33f59c38/subscription_manager.go#L369). 
 
The error occurs at [subscription_manager.go ln 398 on xml.Marshal](https://github.com/Azure/azure-service-bus-go/blob/78c960db000c65f4e32d01371b496d5b33f59c38/subscription_manager.go#L398). The following snippet recreates the error seen:
 
              customProperties := map[string]interface{}{
                             "workertype": "test",
              }
 
              filter := &servicebus.CorrelationFilter{
                             Properties: customProperties,
              }
 
              reqBytes, err := xml.Marshal(filter.ToFilterDescription())

**Comment by richardpark-msft** [comment]
Hi @wzamlynny,

We've moved development of this package into the azure-sdk-for-go repo and I've created a bug to track the issue there: https://github.com/Azure/azure-sdk-for-go/issues/16045.
