### ISSUE TITLE
Error When Receive Message From Topic (Subscription)

### ISSUE THREAD

**Issue by rahman74** [Azure/azure-service-bus-go#208]
`topic, err := ns.NewTopic(te.Name)
	sub, err := topic.NewSubscription(subscriptionName)
    fmt.Println("Error Subs =>",err)
	if err != nil {
		fmt.Println(err)
		return
	}
    var messageHandler servicebus.HandlerFunc = func(ctx context.Context, msg *servicebus.Message) error {
        fmt.Println(msg)

        return msg.Complete(ctx)
    }
	err = sub.Receive(ctx, messageHandler)
    fmt.Println("Error Receive =>",err)
	if err != nil {
		fmt.Println(err)
		return
	}`

And i got error in sub.Receive "The messaging entity could not be found"

**Comment by serbrech** [comment]
ns.NewTopic is not creating a topic in azure. it's creating the go struct that refers to that topic
the topic needs to be present in Azure.
you can create it in the portal, or via the management apis in this library : 

See [topic_manager.go](https://github.com/Azure/azure-service-bus-go/blob/master/topic_manager.go) and [subscription_manager.go](https://github.com/Azure/azure-service-bus-go/blob/master/subscription_manager.go)

**Comment by rahman74** [comment]
> ns.NewTopic is not creating a topic in azure. it's creating the go struct that refers to that topic
> the topic needs to be present in Azure.
> you can create it in the portal, or via the management apis in this library :
> 
> See [topic_manager.go](https://github.com/Azure/azure-service-bus-go/blob/master/topic_manager.go) and [subscription_manager.go](https://github.com/Azure/azure-service-bus-go/blob/master/subscription_manager.go)

Hello, i check in azure portal, the topic already exist with name "purchase_order_events", i want to create a receiver message from the topic, and i got error in line sub.receiver(context,handler) "The message entity could not be found", maybe you have a solution for that?

**Comment by devigned** [comment]
Is the Subscription also created? The error would make me think the Subscription wasn't created yet.

**Comment by rahman74** [comment]
> Is the Subscription also created? The error would make me think the Subscription wasn't created yet.

Hello, i check in azure portal, azure service bus, and check the subcription, its created, this full message error
![image](https://user-images.githubusercontent.com/21357399/108008113-223c8780-7032-11eb-8f09-a7a77e684c78.png)

**Comment by rahman74** [comment]
This full code.

![image](https://user-images.githubusercontent.com/21357399/108009697-d095fc00-7035-11eb-8a3d-4dbac52ecf4b.png)

**Comment by devigned** [comment]
‘SubscriptionName := “”’ seems wrong

**Comment by rahman74** [comment]
> `subscriptionName := “”` seems wrong

whats wrong? i trace/debug its correct variable
![image](https://user-images.githubusercontent.com/21357399/108011339-70a15480-7039-11eb-9490-97441263507b.png)
