### ISSUE TITLE
ListSessions crash

### ISSUE THREAD

**Issue by attouab** [Azure/azure-service-bus-go#209]
This line is crashing 

https://github.com/Azure/azure-service-bus-go/blob/f9ea40a809f9b8f8f8789dc679d2088cc3935be9/message_session.go#L131

The response is being accessed incorrectly. Under the debugger the response looks like this:  

![image](https://user-images.githubusercontent.com/26739456/107952349-8f4c1080-6f91-11eb-957f-2b5d4b8a46d2.png)

**Comment by richardpark-msft** [comment]
Hi @attouab,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus). 

We don't currently export this API in the newer SDK but I wanted to track this bug, which I've done so here: https://github.com/Azure/azure-sdk-for-go/issues/16209
