### ISSUE TITLE
Incorrect ListSessions comment

### ISSUE THREAD

**Issue by attouab** [Azure/azure-service-bus-go#210]
This comment is inaccurate
https://github.com/Azure/azure-service-bus-go/blob/f9ea40a809f9b8f8f8789dc679d2088cc3935be9/message_session.go#L100

Perhaps because the description for the AMQP  [com.microsoft:get-message-sessions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#session-operations) operation is not very clear:

There are 2 session listing function in the [ old .Net API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.getmessagesessions?view=azure-dotnet)

- [GetMessageSessions() ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.getmessagesessions?view=azure-dotnet#Microsoft_ServiceBus_Messaging_QueueClient_GetMessageSessions): Gets the message sessions, enabling you to browse sessions on queues.

- [GetMessageSessions(DateTime)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.getmessagesessions?view=azure-dotnet#Microsoft_ServiceBus_Messaging_QueueClient_GetMessageSessions_System_DateTime_) : Retrieves all message sessions whose session state was updated since lastUpdatedTime.

The [ListSesssions ](https://github.com/Azure/azure-service-bus-go/blob/f9ea40a809f9b8f8f8789dc679d2088cc3935be9/message_session.go#L101) in this SDK ( i.e AMQP  operation [com.microsoft:get-message-sessions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#session-operations) ) is analogous to the  **_[GetMessageSessions(DateTime)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.getmessagesessions?view=azure-dotnet#Microsoft_ServiceBus_Messaging_QueueClient_GetMessageSessions_System_DateTime_)_** overload, which means, it only returns sessions that have a state that has been touched by the specified time (including when the state is nulled), which is fixed to the last 30 min:

https://github.com/Azure/azure-service-bus-go/blob/f9ea40a809f9b8f8f8789dc679d2088cc3935be9/message_session.go#L113

As far as I know, there is no AMQP operation to do what the above comment implies, i.e listing all sessions with active messages (i.e similar to  [GetMessageSessions()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.getmessagesessions?view=azure-dotnet#Microsoft_ServiceBus_Messaging_QueueClient_GetMessageSessions)). 

I don't know what to make of the fact that none of the 2 session listing APIs are available in the latest .Net SDKs (https://github.com/Azure/azure-sdk-for-net/issues/7380)

**Comment by richardpark-msft** [comment]
Hi @attouab,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus). 

We don't currently export this API in the newer SDK but I wanted to track the request, which I've done so here: https://github.com/Azure/azure-sdk-for-go/issues/16209
