### ISSUE TITLE
Message.DeadLetter resulting in *Error(nil)

### ISSUE THREAD

**Issue by rokf** [Azure/azure-service-bus-go#215]
Hello,

after a version lift of this package from `v0.10.10` to `v0.10.11` the `Message`'s `DeadLetter` method returns an `*Error(nil)` that isn't equal to `nil`. Previously it returned `nil` in the same scenario.

1. Was this planned or was this a side effect of some sort?
2. Is there perhaps a bug or are we supposed to do error handling differently in the code that is using the new version of this project/package?

If this was planned, how are we supposed to differentiate errors from successes, if the `err != nil` pattern doesn't work anymore?

Thank you!

Some resources:
- https://github.com/Azure/azure-service-bus-go/blob/v0.10.11/message.go#L240
- https://github.com/Azure/go-amqp/blob/v0.13.6/types.go#L1590

---

**Are we perhaps required to change our queue consumer implementation because of the changes made in https://github.com/Azure/azure-service-bus-go/pull/207?** We use:

- `Receive` for regular queues - https://github.com/Azure/azure-service-bus-go/blob/v0.10.11/queue.go#L227
- `ReceiveOne` for dead letter queues - https://github.com/Azure/azure-service-bus-go/blob/v0.10.11/deadletter.go#L78

**Comment by serbrech** [comment]
The code you point here : https://github.com/Azure/go-amqp/blob/v0.13.6/types.go#L1590 is the String() implementation that gets included in the reason property of the deadletter. so, not the error that is actually returned from calling Deadletter().
Do you mean that you actually get an error back from the Deadletter func or that you see this string in the property on the reason for deadlettering?

from reading the code for deadletter, it seems that we return an error when deadlettering failed. and nil otherwise.

**Comment by rokf** [comment]
Here's an example. The output/behaviour is different between `v0.10.10` and `v0.10.11`.

`v0.10.11` produces:

```
Q: Hello, world!
Queue.ReceiveOne: *Error(nil)
```

while `v0.10.10` produces:

```
Q: Hello, world!
DLQ: Hello, world!
```

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"os"

	servicebus "github.com/Azure/azure-service-bus-go"
)

func main() {
	namespace, err := servicebus.NewNamespace(
		servicebus.NamespaceWithConnectionString(
			os.Getenv("CONNECTION_STRING"),
		),
	)
	if err != nil {
		fmt.Println(err)
		return
	}

	queue, err := namespace.NewQueue(
		os.Getenv("QUEUE_STRING"),
	)
	if err != nil {
		fmt.Println(err)
		return
	}

	deadLetterQueue := queue.NewDeadLetter()

	ctx := context.Background()

	if err := queue.Send(ctx, &servicebus.Message{
		Data: []byte("Hello, world!"),
	}); err != nil {
		fmt.Println(err)
		return
	}

	if err := queue.ReceiveOne(ctx, servicebus.HandlerFunc(func(ctx context.Context, msg *servicebus.Message) error {
		fmt.Printf("Q: %s\n", msg.Data)
		return msg.DeadLetter(
			ctx,
			errors.New("message moved to DLQ"),
		)
	})); err != nil {
		fmt.Printf("Queue.ReceiveOne: %s\n", err)
		return
	}

	if err := deadLetterQueue.ReceiveOne(ctx, servicebus.HandlerFunc(func(ctx context.Context, msg *servicebus.Message) error {
		fmt.Printf("DLQ: %s\n", msg.Data)
		return msg.Complete(ctx)
	})); err != nil {
		fmt.Printf("DeadLetter.ReceiveOne: %s\n", err)
		return
	}

	if err := queue.Close(ctx); err != nil {
		fmt.Println(err)
		return
	}

	if err := deadLetterQueue.Close(ctx); err != nil {
		fmt.Println(err)
		return
	}
}
```

**Comment by richardpark-msft** [comment]
This has been fixed (it involved an underlying issue in go-amqp), so the latest release (0.11.3) will work.

Note that development for this library has now moved to the azure-sdk-for-go [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).
