### ISSUE TITLE
Running queue.Receive method second time leads to freeze receiver and do not process messages

### ISSUE THREAD

**Issue by rafalrygas** [Azure/azure-service-bus-go#216]
### Bug Report

Version: v0.10.11

**What happened?**

Handler method returns an error, so `queue.Receive(ctx, handler)` method stops and also returns an error which is expected behaviour.
However, running `queue.Receive(ctx, handler)` again will lead to freeze receiver and not process any message. With version v.0.10.9 it worked correctly.

**What did you expect or want to happen?**

Processing message correctly after invocation of `queue.Receive(ctx, handler)`

**How can we reproduce it?**

```
import (
        "context"
	servicebus "github.com/Azure/azure-service-bus-go"
)

//...

sbns, _ := servicebus.NewNamespace(servicebus.NamespaceWithConnectionString(connStr))

queue, _  := sbns.NewQueue(name, opts...)

handlerFunc := func(ctx context.Context, msg *servicebus.Message) error {
     return errors.New("sample error")
}

err := queue.Receive(ctx, handlerFunc)

if err != nil {
    println(err.Error())
}

// this line does not process message
err = queue.Receive(ctx, handlerFunc)
if err != nil {
    println(err.Error())
}
```

And receiver is freezed.

**Comment by serbrech** [comment]
Do you have a single message in the queue in this example?

Here, you are not doing any message disposition in the handler, so the message is still locked on the server side by your previous receive.
Erroring out of a handler closes the listener. Failing to consume a message should not return an error. it should take a message disposition (Abandon() likely) and return nil.

There were bugs in go-amqp and in this azure sb library prior to 10.11 that were not respecting pre-fetch, resulting in messages being cached and expiring in memory. I'm not sure for this specific case, but it might be why the behavior changed.

if you expect this to work, then we need to ensure the connection is up when Receive is called, but to be clear, erroring out of a handler means application failure, not message handling failure.

**Comment by rafalrygas** [comment]
Thank you serbrech.
You are right, with this new version of lib adding abandon message to handler resolved problem.
