### ISSUE TITLE
Changing settings of queue freezes receiver without returning any error

### ISSUE THREAD

**Issue by rafalrygas** [Azure/azure-service-bus-go#217]
### Bug Report

Version: v0.10.11

**What happened?**

Messages are received and processed successfully. After changing settings of queue (e.g. Max delivery count) receiving messages is frozen without returning any error 

**What did you expect or want to happen?**

Receive message correctly after changing settings of queue or return an error.

**How can we reproduce it?**

```
import (
        "context"
	servicebus "github.com/Azure/azure-service-bus-go"
)

//...

sbns, _ := servicebus.NewNamespace(servicebus.NamespaceWithConnectionString(connStr))

queue, _  := sbns.NewQueue(name, opts...)

handlerFunc := func(ctx context.Context, msg *servicebus.Message) error {
     println(string(msg.Data))
     return msg.Complete(ctx)
}

err := queue.Receive(ctx, handlerFunc)

if err != nil {
    println(err.Error())
}

Send message (should be processed), changed e.g. max delivery count and send next message. Receiver is frozen and does not handle message.

**Comment by serbrech** [comment]
Hi, thanks for reporting this

How are you changing the settings? In the portal?

**Comment by rafalrygas** [comment]
Yes, I change it in Azure Portal (e.g. Max delivery count in overview bookmark)

**Comment by richardpark-msft** [comment]
Hi @rafalrygas,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

Altering the entity int he Azure Portal results in a detach being sent to the link. In the new SDK we handle this by closing the link and reopening it on the next receive. This allows you to see the reported error (which might indicate a environment trend like network instability) but still allow for a simple recovery when available.

If you'd like to try out the new package we have a migration guide here: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md
