### ISSUE TITLE
amqpMessage.Ignore() is not accessible from servicebus.Message 

### ISSUE THREAD

**Issue by orzel7** [Azure/azure-service-bus-go#218]
After introducing this change: [https://github.com/Azure/go-amqp/commit/825d6e69a40dff9f19d93eb59a3d896aebd89115](url) , it is possible to explicitely control the amqp message pump. It would be very useful to add servicebus.Message.Ignore() method to make it possible ignore message without blocking message pump.

**Comment by richardpark-msft** [comment]
It looks like all the discussion occurred and ended in the PR. Closing this issue.
