### ISSUE TITLE
PUT does not update entities

### ISSUE THREAD

**Issue by cjlapao** [Azure/azure-service-bus-go#222]
When using the Topic/Subscription/Queue Managers PUT, it does not create/update the entity. it does however creates it.

On the subscription, you will get a 409 stating that the entity already exists

**Comment by richardpark-msft** [comment]
Hi @cjlapao, 

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

In the new `azservicebus` package we've split creation and update operations into two separate functions, which make this operation unambiguous.

* An example of CreateQueue: [link](https://github.com/Azure/azure-sdk-for-go/blob/49619d81888257e45ba7a219f2a57d59efb5e4c0/sdk/messaging/azservicebus/admin/example_admin_client_test.go#L43)
* The UpdateQueue function: [link](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus@v0.3.0/admin#Client.UpdateQueue)
