### ISSUE TITLE
Sending message to the queue receive EOF error

### ISSUE THREAD

**Issue by mon7792** [Azure/azure-service-bus-go#223]
**Background.**
We have a long running service listening on the queue.
The service process message arriving in the queue.
As part of processing,
The services can send new message(message count: 1 to 1000) to a new queue.

**Issue**
The service works fine most of the time.
In one case while sending of the newly generated message we got `EOF` error.

**question**
can any one help with understanding the root cause of this error in this context ?

**Comment by serbrech** [comment]
Correct. See : https://github.com/Azure/azure-service-bus-go/issues/237

**Comment by richardpark-msft** [comment]
Hi @mon7792, development for this library has moved over to the the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

I've created an issue ([link](https://github.com/Azure/azure-sdk-for-go/issues/16164)) to track this - we do automatic recovery internally for receiver links and we will want to do the same for sending.
