### ISSUE TITLE
Side effects of not closing Queue and DeadLetter

### ISSUE THREAD

**Issue by rokf** [Azure/azure-service-bus-go#224]
**Are there any possible side effects of not calling `Close` on `Queue` and `DeadLetter` instances before they're discarded and replaced by new instances when even the `Namespace` instance is discarded and replaced?** Does this package perhaps keep some kind of implicit global state in the background that would require the `Close` calls to keep a clean state?

**Comment by richardpark-msft** [comment]
Hi @rokf,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

To your question, the in the new `azservicebus` package closing the top level entity (in our case the `Client`) will shut down the AMQP connection and any other related links, including claim negotation, etc...
