### ISSUE TITLE
Ensure associated-link-name is properly set

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-service-bus-go#226]
https://github.com/Azure/azure-service-bus-go/pull/225 fixed this in one place, but it's required in others.

See https://github.com/Azure/azure-sdk-for-net/search?q=AssociatedLinkName for an example

**Comment by serbrech** [comment]
Is this still active, or is there still more places to set it?
could we create a definitive list of where this needs to be done in servicebus, so that it's easy to track/fix?

**Comment by richardpark-msft** [comment]
(moved to azure-sdk-for-go repo)
