### ISSUE TITLE
Vulnerability in nhooyr.io/websocket

### ISSUE THREAD

**Issue by princjef** [Azure/azure-service-bus-go#227]
There is a vulnerability in the current version of nhooyr.io/websocket that is used by this package (1.8.6), which can potentially cause a DoS vulnerability. It's admittedly a low risk problem here in practice, but updating to 1.8.7+ makes the automated security scanning tools happy.

Here are the details for the CVE: https://snyk.io/vuln/SNYK-GOLANG-NHOOYRIOWEBSOCKET-1244972

**Comment by jhendrixMSFT** [comment]
Fixed in v0.11.4

**Comment by jhendrixMSFT** [comment]
Fixed in v0.11.4
