### ISSUE TITLE
ParsedConnectionFromStr provides no way to use WebSocket (non-AMQPS)

### ISSUE THREAD

**Issue by rovangju** [Azure/azure-service-bus-go#228]
Currently the method at https://github.com/Azure/azure-amqp-common-go/blob/master/conn/conn.go#L65  seems to discard any prefix in the hostname and push `amqps://` in front of the connection string. 

This seems to create some issues for abstractions on the client that want to lean on the parser to figure out the connection (e.g.:
https://github.com/dapr/components-contrib/blob/efd198026fa81dbb93af05d989f78a7fcfa61ce6/pubsub/azure/servicebus/servicebus.go#L254)

A similar situation/need was alluded to in #112 but was maybe lost in the tracking against #93. 

When the #123 PR was made for the Websocket support, it appears it didn't provide any other way to enable websocket other than using ```NamespaceWithWebSocket()``` with a call to ``NewNamespace()`` in `namespace.go` (to set `useWebSocket` to true). 

However, dependents like Dapr and other client users are probably more inclined to use the `NamespaceWithConnectionString()` approach to provide an easy way to configure connectivity. Unfortunately, the implementation of `NamespaceWithConnectionString()` appears to provide no way to override the use of `amqps://` in the connection as it's leaning on `ParsedConnectionFromStr()` from the amqp-common-go lib. 

Proposal ideas:

1. Update azure-amqp-common-go/conn/conn.go to allow a 'protocol' key to override the `amqps://` component of the connection string. (e.g.: `Endpoint=sb://test.servicebus.windows.net;SharedAccessKey=x;SharedAccessKeyName=y;protocol=wss`)
or

2. Update `NamespaceWithConnectionString()` in `namespace.go` to set `useWebSocket` to true with a connection string key. `Endpoint=sb://test.servicebus.windows.net;SharedAccessKey=x;SharedAccessKeyName=y;protocol=wss`)

or ....

3. Something else 😃

**Comment by richardpark-msft** [comment]
Hi @rovangju,

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

We haven't yet exposed the websocket support. I'll file a tracking issue over there since this repo is going to get archived and see what makes sense in the context of the larger SDK.

(issue in azure-sdk-for-go: https://github.com/Azure/azure-sdk-for-go/issues/16201)
