### ISSUE TITLE
Is the retry connection to topic subscription handled in the library ?

### ISSUE THREAD

**Issue by dnwick** [Azure/azure-service-bus-go#236]
Sample code to read messages from subscription,

```
 ctx := context.Background()
    ctx, cancel := context.WithCancel(ctx)
    defer cancel()

    subscription, err := t.NewSubscription(subscriptionName)
    if subscription == nil {
        fmt.Println("NewSubscription is null")
        os.Exit(1)
    }

    err = subscription.Receive(ctx, servicebus.HandlerFunc(func(ctx context.Context, message *servicebus.Message) error {
        fmt.Println(string(message.Data))
        return message.Complete(ctx)
    }))

    if err != nil {
        fmt.Println("FATAL: ", err)
        return
    }
```
Trying to shutdown the internet and reconnect to see whether messages will resume consuming.

Behaviour : If I reconnect within two seconds then consuming resumes. But if the network is down for more than that, following errors received in different occasions,

Test 1
$ go run consumer.go
Hello, World Again!0
Hello, World Again!1
Hello, World Again!2
Hello, World Again!3

FATAL:  context canceled

Test 2
$ go run consumer.go
Hello, World Again!13
Hello, World Again!14
Hello, World Again!15
Hello, World Again!16
Hello, World Again!17
Hello, World Again!18

FATAL:  read tcp 192.168.1.9:65003->168.62.54.52:5671: i/o timeout

Test 3
$ go run consumer.go
Hello, World Again!19
Hello, World Againaa!0
Hello, World Againaa!1

FATAL:  write tcp 192.168.1.9:65270->168.62.54.52:5671: write: can't assign requested address

Test 4
$ go run consumer.go
Hello, World Againaa!2
Hello, World Againaa!3
Hello, World Againaa!4
Hello, World Againaa!5
Hello, World Againaa!6

Hello, World Againaa!7
FATAL:  *Error{Condition: com.microsoft:message-lock-lost, Description: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:9bec591d-d2e4-4fac-bbdd-41f8e31f94cc, TrackingId:0c835ab40002048200cdf77e60f3d1b0_G1_B7, SystemTracker:choreodev1:Topic:testeventtopic|s1, Timestamp:2021-07-18T07:02:53, Info: map[]}

May I know whether I can send any more configuration options to handle this more gracefully ? Or Do I have to handle it by myself

**Comment by serbrech** [comment]
See :

https://github.com/Azure/azure-service-bus-go/issues/237

**Comment by dnwick** [comment]
Thanks for this I will look through it. One thing I note when I go through go-shuttle code is that it uses n Listen[1] function to receive messages from the corresponding subscription. In my code above I used Receive[2] function. Is there a difference of using either ? And what to use when ? So basically Azure sdk is not handling retry I guess

[1]https://pkg.go.dev/github.com/Azure/azure-service-bus-go#Receiver.Listen
[2]https://pkg.go.dev/github.com/Azure/azure-service-bus-go#Subscription.Receive

**Comment by richardpark-msft** [comment]
> Thanks for this I will look through it. One thing I note when I go through go-shuttle code is that it uses n Listen[1] function to receive messages from the corresponding subscription. In my code above I used Receive[2] function. Is there a difference of using either ? 

The big difference between those particular functions is that `Subscription.Receive` will block, whereas `Receiver.Listen` will not. 

In fact, Subscription.Receive is built on top of Receiver.Listen:

```go
func (s *Subscription) Receive(ctx context.Context, handler Handler) error {
   // ...
   handle := s.receiver.Listen(ctx, handler)
   <-handle.Done()
   return handle.Err()
```

> And what to use when ? 

`Receiver.Listen` allows you to avoid blocking but they practically identical otherwise. If you have no issues with the blocking behavior of `Subscription` then it's a good choice since it has the simplest API.

> Also basically Azure sdk is not handling retry I guess
> 

There are some retries built-in but, from your bug, it looks like we've got a gap there. I'll be taking a look at this this week. I'll keep you updated on what I find.

**Comment by dnwick** [comment]
@richardpark-msft Thanks for the reply. Basically in our use case we need the client to ack on every message that received. And only in the description of func (*Subscription) Receive says " Handler must call a disposition action such as Complete, Abandon, Deadletter on the message " Question is how this client acknowledgement handled ? As you mentioned whether using the blocking behaviour provides that by after receiving the message we say " message.Complete(ctx) " or from the code you shown above it seems blocking behaviour handled internally. Basically we need the client to ack so how this provided in the library ? is it from the disposition action ?

**Comment by serbrech** [comment]
Calling msg.Complete() is the ack.
It's sending an Accept message disposition to the broker.
Is that what you mean by "we need the client to ack?"

**Comment by dnwick** [comment]
@serbrech Thanks Yes that is what I wanted to verify. 
Also May I know little bit of information on blocking and non blocking like what does it really mean ? Because both Receive and Listen does this  msg.Complete() for each message as I used in my client code. So if you can please explain little bit in depth about in non-blocking what exactly happens

**Comment by serbrech** [comment]
Receive will wait for. We messages and pass them to your handler. It will not get out of the Receive func unless you cancel the context.

Listen will return you a message and is done.

**Comment by dnwick** [comment]
see below the listen function ,

```
listenerHandle := subReceiver.Listen(ctx, servicebus.HandlerFunc(func(ctx context.Context, message *servicebus.Message) error {
		fmt.Println(string(message.Data))
		return message.Complete(ctx)
	}))
```
Are you saying even though the queue has multiple messages this will only run once and just print one message and exit ? As I have seen it will print all the messages and will keep on listening as well, It will come out of this iff en error occurs . May be I have misunderstood your statement " Listen will return you a message and is done "

**Comment by dnwick** [comment]
I have done more tests and I could see what you meant by blocking call. Thanks.

**Comment by richardpark-msft** [comment]
Looks like this issue was resolved. Closing.
