### ISSUE TITLE
network error not recovered by servicebus

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-service-bus-go#237]
Running in prod, we have identified a few errors that a sender will not recover from.
Once these errors are returned during by a sender operation, it means that the underlying TCP connection is dead and the only way to recover is to recreate the sender.

- syscall.ETIMEDOUT (covered by neterr.Timeout())
- io.EOF
- amqp error with Condition: amqp:internal-error, Description: The service was unable to process the request; please retry the operation.

I think these should be recovered either by servicebus sdk, or maybe even at the lowest level of amqp (for io.EOF for example)

Happy to port the implementation if it's agreed

see go-shuttle for the recovery code we needed to add :
https://github.com/Azure/go-shuttle/blob/main/publisher/errorhandling/recovery.go

**Comment by richardpark-msft** [comment]
This looks sensible to me. We actually have code similar to this in Event Hubs now as well that handles the recovery in addition to the error classification:

* [sender recovery](https://github.com/Azure/azure-event-hubs-go/blob/f16940d69e3254aecd0781ac5ec174eb0dc376d4/sender.go#L287)
* [error classification](https://github.com/Azure/azure-event-hubs-go/blob/f16940d69e3254aecd0781ac5ec174eb0dc376d4/hub.go#L781)

I would definitely be interested in this PR. You'll note that we also recently added in the ability to limit the # of retries as well. 

What do you currently default to for # of retries in your code?

**Comment by serbrech** [comment]
Here is a retry internally for normal send failure.
So if it gets to my reconnection logic, I just retry once and failed.
Keeping it simple.

**Comment by richardpark-msft** [comment]
We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

Error handling and making errors programatically useful is being tracked here: https://github.com/Azure/azure-sdk-for-go/issues/15610
