### ISSUE TITLE
send and receive batch messages

### ISSUE THREAD

**Issue by mcgradycchen** [Azure/azure-service-bus-go#24]
Is it possible to send and receive batch messages azure to service bus?

**Comment by devigned** [comment]
Right now, the feature has not been implemented, but it is on the list to implement before the library is feature complete.

I expect it will look similar to the [EventHub implementation](https://github.com/Azure/azure-event-hubs-go/blob/2abafea1af288084b5b20bc9e251a3ed515dd411/hub.go#L289-L305).

I'll try get this added this week.

Just out of curiosity, why do you want to send batch messages? Is it simply for performance reasons?

**Comment by devigned** [comment]
This is a long past due.

**Comment by anjoshigor** [comment]
I know this is closed, but I could not find any code for receiving batch messages. How can I perform this operation?

**Comment by devigned** [comment]
Give this Event Hub example a look: https://github.com/Azure/azure-event-hubs-go/tree/master/_examples/batchprocessing.

Really, receive batching is something that at the protocol level with prefetch. If you want to build up a batch in your receiver before taking some action, then you can build a stateful receiver as shown in the above example.
