### ISSUE TITLE
entityreceiver.RenewLocks mutex makes concurrent message lock renewal very slow

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-service-bus-go#247]
https://github.com/Azure/azure-service-bus-go/blob/47f464057d3e1f3bcbbdf59f52aca31bbae037b0/entity.go#L195-L196

This came as a suprise. my renewlocks routine was using the receiving entity as the gateway to call RenewLocks.
Each message handled would start the goroutine and pass the subscription to renew the locks on that message.
This lock made each RenewLocks call block the other messages handled concurrently. at high concurrency, they were failing to call RenewLocks in time.

I changed the my lockrenewer to take in an RPCClient directly, which already implements recovery, and claim auto-refresh internally. I don't see why there would be any concurrency issue, and my lockrenewer goroutine now works as expected.

**Comment by richardpark-msft** [comment]
This should now be resolved as of [`v0.11.1`](https://github.com/Azure/azure-service-bus-go/releases/tag/v0.11.1)
