### ISSUE TITLE
Where is the code to periodically refresh the auth token?

### ISSUE THREAD

**Issue by ivarec** [Azure/azure-service-bus-go#251]
I think I'm being affected by this old issue: #116. The symptoms and the error messages are exactly the same.

After digging up a little, I found the PR that was supposed to have fixed this back in 2019: https://github.com/Azure/azure-service-bus-go/pull/137

However, I can't find this PR's code anywhere in master. Am I missing something?

Thanks in advance!

**Comment by serbrech** [comment]
https://github.com/Azure/azure-service-bus-go/blob/0f63768a95d50685ff742184c6b3865ddbf2155b/receiver.go#L382
the negotiateClaim starts a goroutine in the background that refreshes the claim using the auth token.

Here is the code : 
https://github.com/Azure/azure-service-bus-go/blob/0f63768a95d50685ff742184c6b3865ddbf2155b/namespace.go#L257

Note that there was a recent fix to retry on failure:  
https://github.com/Azure/azure-service-bus-go/pull/245

**Comment by richardpark-msft** [comment]
(NOTE: We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

Closing as it appears the question was answered and a fix had been made in the same area.
