### ISSUE TITLE
Support for Auto Renewal of Message Lock

### ISSUE THREAD

**Issue by sachithKay** [Azure/azure-service-bus-go#252]
I see that message locking mechanism has been introduced with https://github.com/Azure/azure-service-bus-go/pull/35.
However, it seems this requires adding routines to keep track of messages/locks. 

Is an auto-renewal mechanism in the works similar to https://docs.microsoft.com/en-us/python/api/azure-servicebus/azure.servicebus.autolockrenewer?view=azure-python ? This idea has been discussed in the https://github.com/Azure/azure-service-bus-go/pull/35 but doesn't seem to be implemented yet.

**Comment by richardpark-msft** [comment]
Unfortunately this doesn't exist, at the moment, in the azure-service-bus-go SDK. 

(closing for now - I'll ping back here if there's additional news on that front)
