### ISSUE TITLE
Auth token is not refreshed for $management path

### ISSUE THREAD

**Issue by orzel7** [Azure/azure-service-bus-go#253]
From logs i can see that NegotiateClaim function was called only once for management queue. As a result, any functionality based on management queue fails after token expiration time(2 hours).

**Comment by richardpark-msft** [comment]
(note for external visitors: We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

@orzel7, I think you've nailed down why all of these $management path calls are an issue. We've fixed this in the new package by using the same claim negotiation for management links that we use for sender/receiver links.
