### ISSUE TITLE
servicebus.Message receivers are orphaned when calling servicebus.Receiver.Recover()

### ISSUE THREAD

**Issue by Lknechtli** [Azure/azure-service-bus-go#262]
When servicebus.Receiver.Recover() is called;
* The servicebus.Receiver.Closed state is set to false and never set back to true if the Receiver successfully recovers.
* Messages received on handler function using the servicebus.Receiver contain a reference to the original amqp.Receiver, rather than the servicebus.Receiver. This means that recovering the Receiver does not update the session / links on the messages received on the Receiver.

These problems mean that if you try to recover Receiver then perform any action on a message linked to it, all actions will result in an `amqp: connection closed` error

**Comment by richardpark-msft** [comment]
Hi @Lknechtli, 

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

The bug you mentioned has been fixed there by allowing a fallback to the management link if the original link has been closed (like you mention, if we recover internally).
