### ISSUE TITLE
Issues Updating to Recent Releases

### ISSUE THREAD

**Issue by halspang** [Azure/azure-service-bus-go#264]
Howdy all. Recently, the team working on [dapr](github.com/dapr/dapr) tried to update the various sdk/library packages associated with Azure ServiceBus in golang.

When we did this, we ran into frequent link detached errors. These would occur consistently at exactly 1 hour from initialization and reconnection was not possible. The only solution we had was to revert our upgrades, which isn't ideal.

Any guidance on this would be great. Given the consistency and severity of the problem, I wonder if there's some setup or call difference that we missed when we upgrade the libraries.

Here's a link to the commit where we reverted the upgrades: [versions](https://github.com/dapr/components-contrib/commit/f5d8317c41c5bb7a077855df9f60c9ff42ac012a#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6).

This was specifically using topics and we saw it both while trying to read from and publish to the topics. The callout that we don't have the correct claim to listen is interesting to me as it listens with that same connection string for an hour before failing. Here's an example of the error message we received.

```
{"app_id":"pubsub-workflow","instance":"pubsub-workflow-app-7c8dc8678b-hnchl","level":"error","msg":"azure service bus error: error receiving message on topic slowtopic, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'tazkhmKOckJX_-5TWVOcgS6dUgLEikvmJjTfMkIRajgov8ei-ghgsA' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://nightly-servicebus.servicebus.windows.net/slowtopic/subscriptions/pubsub-workflow'.. TrackingId:08ad587a77b841b3bdcdb0074d0ff789_G17, SystemTracker:gateway7, Timestamp:2021-11-12T22:15:03, Info: map[]}","scope":"dapr.contrib","time":"2021-11-12T22:15:03.90860438Z","type":"log","ver":"edge"}
```

Please let me know if you need any clarifying info on this.

**Comment by richardpark-msft** [comment]
Hi @halspang, 

(I know we talked already, but for anyone else coming up on this issue):

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus). 

What we did find as we were working on the new library was that there some of the links were actually being put onto separate links, which could cause a link/connection to look idle even if the user was actively doing things within the SDK itself. This has been changed.

In addition some areas were not consistently using the same auto-claim-renewal logic. This has also been changed in the latest package.
