### ISSUE TITLE
Lock renewal 

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-service-bus-go#34]
Hi, 

I'm currently working on supporting message lock renewal via AMQP on SB using the [request-response flow here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#message-renew-lock). There are a couple of changes that will likely be needed in [vcabbage to support](https://github.com/lawrencegripper/ion/issues/157) it but ideally I thought this might be a useful contribution back to this library. 

Before I go further I wanted to check if it would be of use and if this was something that was already being worked on?

Current WIP is here (please excuse the rest of the mess) - https://github.com/lawrencegripper/ion/blob/master/internal/pkg/servicebus/amqpconnection.go#L196

**Comment by lawrencegripper** [comment]
I've fixed up the issue with the unmarshalling of null types in the vcabbage lib and that is now merged: https://github.com/vcabbage/amqp/pull/117.

**Comment by devigned** [comment]
This is definitely a feature we'd like to have in the library. I haven't started it yet, so if you have the time, I'll happily review a PR with the feature.

**Comment by lawrencegripper** [comment]
After working with the SB team have a resolution to an issue preventing lock renewal from messages which didn't originate over AMQP. I'm going to propose changes to vcabbage lib to fix that issue and once completed hopefully revisit the WIP PR.

**Comment by marstr** [comment]
This functionality was added in #35
