### ISSUE TITLE
Abstract OpenTracing and OpenCensus

### ISSUE THREAD

**Issue by marstr** [Azure/azure-service-bus-go#39]
Adding observability back into distributed systems isn't trivial, but there are a handful of technologies that help. The entry point into any of those technologies is a reliable and well-thought-out instrumentation. Extending instrumentation into libraries helps to bring clarity to the source of unexpected behavior and performance characteristics. Today, this repository uses OpenTracing for instrumentation purposes. However, we believe there are some advantages to switching to OpenCensus. This issue is here to track the work associated with that switch.

| Link | Description |
| :-----|:-------------|
| https://opencensus.io | The official OpenCensus site. |
| http://opentracing.io | The official OpenTracing site. |

**Comment by cjhpaul** [comment]
Sounds good, but any thoughts on keeping the OpenTracing compatibility for those who are using it?

**Comment by devigned** [comment]
We should add an abstraction layer for tracing. Perhaps, a `OpenTracer` interface or something. OpenTracing and OpenCensus are not that different. I think we could do this with minimal pain.
