### ISSUE TITLE
Automatically infer test location when not provided

### ISSUE THREAD

**Issue by marstr** [Azure/azure-service-bus-go#40]
When the tests are executed, they pull the Azure Region that should be used from the Environment Variable `TEST_SERVICEBUS_LOCATION`. When that variable is not set, it should be inferred from the resource group that was specified.

**Comment by brainsnail** [comment]
I'll take a look at this one 😄

**Comment by devigned** [comment]
I'm going to close this issue as the TF setup will output this information by default.

**Comment by brainsnail** [comment]
Thanks. Sorry about not following up on this ☹️
