### ISSUE TITLE
Add Go to Aggregate Repository

### ISSUE THREAD

**Issue by marstr** [Azure/azure-service-bus-go#45]
The repository [Azure/azure-service-bus](https://github.com/Azure/azure-service-bus) contains a list of official Microsoft Service Bus libraries across many languages. Today, that repository has no reference to the Go assets in this repository.

To close this issue, the following should be accomplished:
- [ ] The aggregate repository should have a sub-module pointing at the most recent release of this repository.
- [ ] The documentation there should be updated to include a link to our documentation and samples, which can be found at: https://godoc.org/github.com/Azure/azure-service-bus-go

**Comment by richardpark-msft** [comment]
Moving this issue here: https://github.com/Azure/azure-sdk-for-go/issues/16198
