### ISSUE TITLE
Expand Queue Examples to Topic, Subscription

### ISSUE THREAD

**Issue by marstr** [Azure/azure-service-bus-go#57]
You can see the list of examples for this package here: 
https://godoc.org/github.com/Azure/azure-service-bus-go#pkg-examples

At time of writing, all of the examples above use a Service Bus Queue. Expanding the available examples to cover using Topics and Subscriptions would be a valuable expansion.

**Comment by devigned** [comment]
I think this is pretty well covered. If someone would like to see more examples, please comment and reopen.
