### ISSUE TITLE
Error calling amqp's deprecated LinkSessionFilter

### ISSUE THREAD

**Issue by cjhpaul** [Azure/azure-service-bus-go#65]
Based on https://github.com/vcabbage/amqp/commit/737d254fced3c8c602d642fd6bce8488a0fa9819, LinkSessionFilter is no longer used in the latest of pack.ag/amqp. But receiver.go still uses the deprecated one.
Can someone update this?
Thanks.

**Comment by marstr** [comment]
Fixed:
https://github.com/Azure/azure-service-bus-go/blob/cac7a6f976ee8139b3a20bfd068d2657604816a2/receiver.go#L293
