### ISSUE TITLE
Add concurrent receiver handling for streaming receiver

### ISSUE THREAD

**Issue by devigned** [Azure/azure-service-bus-go#88]
`Queue.Receive` and `Subscription.Receive` should take an option `QueueWithMaxConcurrency(maxConcurrency int)` which will allow `maxConcurrency` number of concurrent messages to be handled.

Right now, `Queue.Receive` and `Subscription.Receive` handles one message at a time, which can be slower than expected. A consumer could create multiple clients and consume from the same queue to achieve the same behavior, but it would have the side effect of creating a new tcp connection, session and link for each client.

### Current flow
```
Receive:
  msg <-- Broker
  msg (send disposition) --> Broker
  <-- (receive ack) Broker
```

### Updated flow:
```
Receive(maxConcurrency):
  go(worker pool with maxConcurrency):
      msg <-- Broker
      msg (send disposition) --> Broker
      <-- (receive ack) Broker
```

**Comment by mcgradycchen** [comment]
Hi devigned,

Sorry to jump into your comments.

I don't think this library need to support concurrent message handling. Adding an example about how to set `prefetchCount` and process messages with go worker pool is enough.

A library implements more features, it will have more bugs and be hard to maintain. What's worse, it may not bring benefit for most users.


Thanks,
McGrady

**Comment by devigned** [comment]
I'm glad to hear your take on this @mcgradychen. Thank you.

We have been wrestling with that balance internally on the team. In the .NET and Java versions of the library, a developer is able to specify the max concurrency. Turns out, it's a pretty popular feature.

We took a similar approach with creating a [batch processing example for EventHubs](https://github.com/Azure/azure-event-hubs-go/blob/master/_examples/batchprocessing/main.go), rather than adding a batch processor (Ignore the fact the example is not really in an example. It will be moved to a real example soon.). It worries me that folks will have a hard time discovering the example vs. seeing an option or func in the package.

Perhaps, we'll provide the documentation thru an example first. From there, if we end up with request or a PR to include concurrent processing, we'll think about including it.

Thoughts? You interested in adding an example :)?

**Comment by anjoshigor** [comment]
Hi,

I'm having some troubles on receiving messages from a topic concurrently using `Subscription.Receive` function. Does anyone have an working example such as the one given by McGrady on Queue client?

Thanks in advance!

**Comment by richardpark-msft** [comment]
Hi all, development for the Service Bus package has been moved to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

This particular issue doesn't exist in the current API surface anymore, as we've removed the callback API surface and replaced it with a pull-based mechanism (still using AMQP).

An example of this is here: [link](https://github.com/Azure/azure-sdk-for-go/blob/49619d81888257e45ba7a219f2a57d59efb5e4c0/sdk/messaging/azservicebus/example_receiver_test.go#L58), which uses the ReceiveMessages() function to get a fixed quantity of messages, which can be called easily in a loop.

I'm closing this here, as this repo is being archived, but please feel free to file an issue in azure-sdk-for-go if you'd like more information or discussion.
