### ISSUE TITLE
Add web socket support

### ISSUE THREAD

**Issue by devigned** [Azure/azure-service-bus-go#93]
### Expected Behavior
Should be able to connect to Event Hubs via web sockets rather than over the standard AMQP ports to better support common open ports.

### Actual Behavior
The library only supports common AMQP ports.

**Comment by sopatwar** [comment]
Any approximate ETA for this enhancement ?

Thanks,
Sourabh

**Comment by devigned** [comment]
This is something I've wanted to add for a while. I'll see if I can get you a batch to test out late this week or early next.

**Comment by sopatwar** [comment]
@devigned Great!
Will wait for your update.

Thanks,
Sourabh

**Comment by sopatwar** [comment]
@devigned 
Do you have any update for me ?

Thanks,
Sourabh

**Comment by devigned** [comment]
Sorry to say that I haven't been able to get to this feature due to other work priorities. I will try to get it out as soon as possible.

**Comment by devigned** [comment]
Sorry for the long wait, but here's a branch with WSS support. I'll be adding an example shortly and more tests shortly.

**Comment by sopatwar** [comment]
@devigned Thanks for committing this!
Will wait for #124 to get sorted out and then test this out.

-Sourabh

**Comment by devigned** [comment]
@sopatwar, I'm hoping #124 gets sorted out quickly, but if you use `dep` or `vgo` you should be able to use the SDK without the delay of waiting on #124.

**Comment by sopatwar** [comment]
@devigned 
I need to use the new web sockets API from on-prem (go through IT-managed https proxy)
I was thinking about using [ReverseProxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy)
Reference:  [Golang  1.12 docs](https://golang.org/doc/go1.12#net/http/httputil)

Is this supported by the API, or is it feasible to extend the API ?

Thanks,
Sourabh

**Comment by sopatwar** [comment]
@devigned 
I need to use the new web sockets API from on-prem (going through IT-managed HTTP proxy)
The golang websocket package cannot handle this.
An alternative library suggested in the godoc is [goriila](https://github.com/gorilla/websocket)

Can you make the Azure API configurable to use gorilla web socket as an option?
This would enable using web socket via http proxy.

Thanks,
Sourabh

**Comment by devigned** [comment]
I was toying with the idea of allowing consumer of the library to supply their own `net.Conn`. That way consumer can be as flexible as they wish. Thoughts?

**Comment by vcabbage** [comment]
I think the tricky part is that the gorilla package is designed for the more typical websocket use case of sending messages back and forth, rather than purely as a data transport like `x/net/websocket` exposes and AMQP expects. You'd likely need to write an adapter to make the gorilla client work as a `net.Conn`. The other option would be to update `x/net/websocket` to support proxying.

**Comment by devigned** [comment]
One other option that looks like it could work is: https://github.com/nhooyr/websocket. Using the `DialerOptions` one could configure an `http.Transport` to use a proxy.

**Comment by sopatwar** [comment]
Although I like @vcabbage's suggestion (update x/net/websocket to support proxying), that might be more involved. Additionally, it will only be available in the latest Golang version (or beyond).

A 3rd-party package approach, such as the one you pointed out [nhooyr](https://github.com/nhooyr/websocket), seems better.

Thanks,
Sourabh

**Comment by vcabbage** [comment]
> Additionally, it will only be available in the latest Golang version (or beyond).

The `x` packages are developed outside of the main Go repo and not considered part of the stdlib. Any changes to it should be available immediately and hypothetically support any Go version (depends on APIs in use of course). Or did you mean something else?

I think the nhooyr library would be similar to gorilla in that it would need a `net.Conn` adapter.

**Comment by sopatwar** [comment]
> >  Any changes to it should be available immediately and hypothetically support any Go version (depends on APIs in use of course). Or did you mean something else?
> 
oh ok, I didn't know about this. I was concerned about using the latest Golang version.

**Comment by vcabbage** [comment]
Doesn't look like `x/net/http` uses `net/http`, so wrapping one of the others is likely the easier route.

**Comment by vcabbage** [comment]
Here's a wrapper for gorilla/websocket that seems to work, might be a useful starting point. It uses the underlying `net.Conn` instead of the `websocket.Conn` fields (`SetReadDeadline`, etc) because they don't appear to fully adhere to the `net.Conn` requirements.

```go

type WSConn struct {
	ws *websocket.Conn
	net.Conn
	reader io.Reader
}

func NewWSConn(urlStr string) (*WSConn, error) {
	conn, _, err := (&websocket.Dialer{}).Dial(urlStr, http.Header{
		"Sec-WebSocket-Protocol": []string{"amqp"},
	})
	if err != nil {
		return nil, err
	}

	return &WSConn{ws: conn, Conn: conn.UnderlyingConn()}, nil
}

func (c *WSConn) Read(p []byte) (int, error) {
	if c.reader != nil {
		n, err := c.reader.Read(p)
		if err == io.EOF {
			c.reader = nil
			return n, nil
		}
		return n, err
	}

	_, r, err := c.ws.NextReader()
	if err != nil {
		return 0, err
	}

	n, err := r.Read(p)
	if err == io.EOF {
		return n, nil
	} else {
		c.reader = r
	}
	return n, err
}

func (c *WSConn) Write(p []byte) (int, error) {
	wc, err := c.ws.NextWriter(websocket.BinaryMessage)
	if err != nil {
		return 0, err
	}
	n, err := wc.Write(p)
	if err != nil {
		return n, err
	}
	return n, wc.Close()
}
```

**Comment by nhooyr** [comment]
@vcabbage my library doesn't need a net.Conn wrapper, you can configure the http.Transport to use a HTTP proxy as mentioned by @devigned

**Comment by vcabbage** [comment]
@nhooyr My library (https://github.com/vcabbage/amqp; the underlying AMQP implementation) requires a `net.Conn` :) Unless I've missed something a wrapper would be required to have yours fulfill that requirement.

**Comment by nhooyr** [comment]
Yes, it would but all the other libraries would as well. With mine, you don't need to handle the proxy logic or the net.Dial yourselves. You just use net/http.

**Comment by vcabbage** [comment]
No argument from me on that :) I don't have any particular preference on the issue, only involving myself because of the AMQP package.

It does appear that your library would need to expose the underlying `net.Conn` in order to be properly wrapped.

**Comment by nhooyr** [comment]
You should be able to wrap it without exposing the underlying net.Conn.

Why use WebSockets here at all versus using HTTP Connect to tunnel over HTTP?

**Comment by devigned** [comment]
@nhooyr, thanks for the clarifying. 

Also, love the use of ctx across the API. Ran across your lib via a reddit post and appreciated the [comparison in the readme](https://github.com/nhooyr/websocket#comparison).

**Comment by vcabbage** [comment]
> You should be able to wrap it without exposing the underlying net.Conn.

It needs a way to implement the deadline methods of `net.Conn`. To be fair, I'm not certain my example with the gorilla wrapper properly implements those methods either, something more involved may be required. They're a bit tricky considering they need to unblock the reader/writer without killing the connection.

> Why use WebSockets here at all versus using HTTP Connect to tunnel over HTTP?

AMQP 1.0 can be used directly over TCP, TLS, or on top of WebSockets, as defined by the spec.

**Comment by nhooyr** [comment]
> It needs a way to implement the deadline methods of net.Conn. To be fair, I'm not certain my example with the gorilla wrapper properly implements those methods either, something more involved may be required. They're a bit tricky considering they need to unblock the reader/writer without killing the connection.

Your example seems solid to me. It'd be very similar with my library. gorilla/websocket just makes it easier because it doesn't use context.Context. For mine, you'd have to store a read and write context on the structure and use it for reading/writing and update it when the SetDeadline methods are called.

**Comment by nhooyr** [comment]
My library now natively supports adapting a *websocket.Conn as a net.Conn to make tunnelling arbitrary protocols over WebSockets very easy.

https://godoc.org/nhooyr.io/websocket#NetConn
