### ISSUE TITLE
Add module specific error with ErrorCondition

### ISSUE THREAD

**Issue by vsaroopchand** [Azure/azure-service-bus-go#95]
The SDK [returns ](https://github.com/Azure/azure-service-bus-go/blob/7dafc265e8a87e9d1b4070e6f4a8dad19416977a/receiver.go#L288) a common.Retryable error type which hides the amqp [ErrorConditions](https://github.com/Azure/azure-service-bus-go/blob/7dafc265e8a87e9d1b4070e6f4a8dad19416977a/message.go#L98) making it difficult to write exception handling logic. Can we return a module specific exception that has the ErrorCondition and relevant information for SDK users?

This will be helpful for the ongoing pubsub [proposal ](https://github.com/google/go-cloud/pull/1207) for go-cloud.

**Comment by richardpark-msft** [comment]
NOTE: We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

I have a bug submitted to track this in the new package: https://github.com/Azure/azure-sdk-for-go/issues/15644
