### ISSUE TITLE
Add Exists check on Queue, Topic, Subscription, etc.

### ISSUE THREAD

**Issue by vsaroopchand** [Azure/azure-service-bus-go#96]
Currently, checking for existence of a Queue, Topic or Subscription involves using Manage Permissions on the Namespace (TopicManager, SubscriptionManager) to Get the Entity. Restricted Permission (Send, Listen) has to rely on connection failure to test for existence. Can we add an 'Exists' Boolean check on these types that work without management permission? 
 
Proposal:
Send Permission Only
- Topic.Exists - true or false after establishing temporary link
- Subscription.Exists - should it fail if no Send or Manage permission?

Listen Permission Only
- Topic Exists - should it fail if no Send or Manage permission?
- Subscription.Exists - true or false after establishing temporary link

Management Permission
- Topic Exists - establish temporary link or use Management to test existence of the Entity
- Subscription Exists - establish temporary link or use Management to test existence of the Entity

**Comment by devigned** [comment]
@Azure/service-bus what are you thoughts on this? How should we approach differentiating these scenarios?

**Comment by nemakam** [comment]
@devigned - I guess this should be doable on the client side. Essentially, opening a link on service to a non existing entity should already throw today. Send and Listen can be done by appropriately using sendingLink and receivingLink. For management, use the managementClient equivalent to do a QueueExists() check.

**Comment by devigned** [comment]
@nemakam I think the toughest part is to figure out what access level the credential has. Does it have rights to listen, send or manage? Is there a way to determine the rights?

**Comment by nemakam** [comment]
I'm not sure I understand your concern completely. 
Talking in terms of AMQP, you'll anyway need to send the token over to CBS before you initiate this link right. That should take care of it. If the authentication token they provided has only send permissions, then trying to open a receivingAmqpLink will throw unauthorized exception.

**Comment by devigned** [comment]
I was hoping there might be some endpoint like /me which would provide metadata about rights for the current identity. It would be easier than sniffing based on errors received.

**Comment by nemakam** [comment]
I'd think creating link provides more benefits. Once that link is created, sending / receiving is now pretty quick even for the first message. If you have manage permissions, you should be able to retrieve all the access tokens and validate.

**Comment by gavinfish** [comment]
It needs to provide the entity path when sending the token over to CBS. For now, it will return `404` regardless which token you provide if the entity does not exist. 

Test code:
```
        var listen = "$LISTEN_CONN_STR"
        var entityPath = "$TOPIC_NAME"
	namespace, err := servicebus.NewNamespace(servicebus.NamespaceWithConnectionString(listen))
	if err != nil {
		log.Error(err)
		return
	}
	cxt := context.Background()

	topic, err := namespace.NewTopic(entityPath)
	if err != nil {
		log.Error(err)
		return
	}
	err = topic.Send(cxt, servicebus.NewMessageFromString("test"))
	if err != nil {
		log.Error(err)
		return
	}
```

Result: `unhandled error link ***: status code 404 and description: The messaging entity 'sb://**.servicebus.windows.net/helloworld1' could not be found. TrackingId:***, SystemTracker:**.servicebus.windows.net:helloworld1, Timestamp:2019-07-18T02:11:52`

So should we approach differentiating these scenarios or just depend on the CBS behavior?

**Comment by devigned** [comment]
@gavinfish that's an interesting insight. I think the 404 here would be enough to say no, the entity does not exist.

I'm guessing there will be a different error when the token is unauthorized for the entity path. It would be a good case to test.

I'm still unclear on how we should surface `Exists()`. Should exists really be `Stat()` or something like that which would return if the entity exists, what you can do with it (read, write, manage) and other details?

**Comment by richardpark-msft** [comment]
Hi all, 

We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus).

Looking at this issue it looks like the basic functionality exists by doing as @nemakam had recommended, which is to just try the activity and if it succeeds then you can move onto the next stage, which is using it.

With regards to @devigned's earlier concern (about sniffing the error), I believe https://github.com/Azure/azure-sdk-for-go/issues/15610 covers the sentiment of trying to make our errors programatically usable. I'll add a link to this issue as well.
